/* Organic agent bundle — generated by agent/build.mjs. Do not edit. */
/* ---- agent/bezel.js ---- */
/**
 * bezel.js — the phone drawn over the page.
 *
 * A fixed rounded frame with an inner shadow ring and a 1px light rim, the
 * Dynamic Island as a black pill at the top, and the home indicator bar at the
 * bottom. Everything here is pointer-events:none and lives at the top of the
 * stack, so it cannot block a scroll or a click anywhere on the real page.
 *
 * Sites rewrite their own DOM constantly. A MutationObserver re-attaches the
 * bezel if it is removed, throttled to at most once a second so a busy feed
 * cannot turn this into a re-render loop.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.bezel) return;

  var ID = "__organic_bezel";
  var Z = 2147483640; // just under the cursor, which must sit over everything
  var node = null;
  var lastAttach = 0;
  var observer = null;

  function css() {
    return (
      "#" + ID + "{position:fixed;inset:0;z-index:" + Z + ";pointer-events:none;" +
      "contain:strict;}" +
      "#" + ID + " .frame{position:absolute;inset:0;border-radius:46px;" +
      "box-shadow:inset 0 0 0 1px rgba(255,255,255,.28)," +
      "inset 0 0 0 3px rgba(0,0,0,.92)," +
      "inset 0 0 22px 6px rgba(0,0,0,.45);}" +
      "#" + ID + " .island{position:absolute;top:10px;left:50%;" +
      "transform:translateX(-50%);width:104px;height:31px;border-radius:18px;" +
      "background:#000;box-shadow:0 0 0 1px rgba(255,255,255,.06);}" +
      "#" + ID + " .home{position:absolute;bottom:7px;left:50%;" +
      "transform:translateX(-50%);width:134px;height:5px;border-radius:3px;" +
      "background:rgba(0,0,0,.72);box-shadow:0 0 0 1px rgba(255,255,255,.18);}"
    );
  }

  function build() {
    var el = document.createElement("div");
    el.id = ID;
    el.setAttribute("aria-hidden", "true");
    var style = document.createElement("style");
    style.textContent = css();
    el.appendChild(style);
    ["frame", "island", "home"].forEach(function (name) {
      var part = document.createElement("div");
      part.className = name;
      el.appendChild(part);
    });
    return el;
  }

  function attach() {
    var host = document.body || document.documentElement;
    if (!host) return;
    if (node && node.isConnected) return;
    node = build();
    host.appendChild(node);
    lastAttach = Date.now();
  }

  function watch() {
    if (observer || !root.MutationObserver) return;
    observer = new root.MutationObserver(function () {
      if (node && node.isConnected) return;
      if (Date.now() - lastAttach < 1000) return; // at most once a second
      attach();
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
  }

  O.bezel = {
    mount: function () {
      if (document.body) {
        attach();
        watch();
      } else {
        document.addEventListener("DOMContentLoaded", function () {
          attach();
          watch();
        });
      }
      return true;
    },
    /** The home bar's hit box, so the panel's grabber can sit exactly on it. */
    homeRect: function () {
      var bar = node && node.querySelector(".home");
      return bar ? bar.getBoundingClientRect() : null;
    },
    el: function () {
      return node;
    },
  };
})(window);

/* ---- agent/cursor.js ---- */
/**
 * cursor.js — the green thing Alex watches.
 *
 * A #39FF7A dot with a soft halo, a ring that pulses outward, and a small name
 * label. moveTo() glides along a slightly curved path with eased, wobbly steps
 * at 60fps: never a jump, never a straight line. press() squashes the dot and
 * throws a ripple where it stands.
 *
 * Pointer-events none and the highest z-index there is, so it is visible over
 * the page and never in the way of it. Like the bezel it re-attaches itself if
 * the page throws it away.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.cursor) return;

  var ID = "__organic_cursor";
  var Z = 2147483647;
  var node = null;
  var dot = null;
  var label = null;
  var lastAttach = 0;
  var observer = null;
  var x = 0;
  var y = 0;
  var moving = null; // a token so a new move cancels the one in flight

  function css() {
    return (
      "#" + ID + "{position:fixed;left:0;top:0;z-index:" + Z + ";" +
      "pointer-events:none;will-change:transform;}" +
      "#" + ID + " .dot{position:absolute;left:-9px;top:-9px;width:18px;" +
      "height:18px;border-radius:50%;background:#39FF7A;" +
      "box-shadow:0 0 10px 3px rgba(57,255,122,.75),0 0 28px 12px rgba(57,255,122,.28);" +
      "transition:transform 90ms ease-out;}" +
      "#" + ID + " .ring{position:absolute;left:-9px;top:-9px;width:18px;" +
      "height:18px;border-radius:50%;border:2px solid rgba(57,255,122,.7);" +
      "animation:__organic_pulse 1.6s ease-out infinite;}" +
      "#" + ID + " .name{position:absolute;left:16px;top:8px;font:600 11px/1.4 " +
      "-apple-system,BlinkMacSystemFont,'SF Pro Text',system-ui,sans-serif;" +
      "color:#0b1b10;background:#39FF7A;padding:1px 6px;border-radius:7px;" +
      "white-space:nowrap;box-shadow:0 1px 6px rgba(0,0,0,.35);}" +
      "#" + ID + " .ripple{position:absolute;left:-9px;top:-9px;width:18px;" +
      "height:18px;border-radius:50%;border:2px solid rgba(57,255,122,.9);" +
      "animation:__organic_ripple 420ms ease-out forwards;}" +
      "@keyframes __organic_pulse{0%{transform:scale(1);opacity:.85}" +
      "100%{transform:scale(2.6);opacity:0}}" +
      "@keyframes __organic_ripple{0%{transform:scale(1);opacity:.9}" +
      "100%{transform:scale(3.4);opacity:0}}"
    );
  }

  function build() {
    var el = document.createElement("div");
    el.id = ID;
    el.setAttribute("aria-hidden", "true");
    var style = document.createElement("style");
    style.textContent = css();
    el.appendChild(style);
    var ring = document.createElement("div");
    ring.className = "ring";
    dot = document.createElement("div");
    dot.className = "dot";
    label = document.createElement("div");
    label.className = "name";
    label.textContent = O.cursorName || "Bea";
    el.appendChild(ring);
    el.appendChild(dot);
    el.appendChild(label);
    return el;
  }

  function attach() {
    var host = document.body || document.documentElement;
    if (!host) return;
    if (node && node.isConnected) return;
    node = build();
    host.appendChild(node);
    place();
    lastAttach = Date.now();
  }

  function watch() {
    if (observer || !root.MutationObserver) return;
    observer = new root.MutationObserver(function () {
      if (node && node.isConnected) return;
      if (Date.now() - lastAttach < 1000) return;
      attach();
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
  }

  function place() {
    if (node) node.style.transform = "translate3d(" + x.toFixed(2) + "px," + y.toFixed(2) + "px,0)";
  }

  var easeInOut = function (t) {
    return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
  };

  function moveTo(tx, ty, opts) {
    opts = opts || {};
    attach();
    var ms = Math.max(120, opts.ms || 520);
    var sx = x;
    var sy = y;
    var dx = tx - sx;
    var dy = ty - sy;
    var dist = Math.sqrt(dx * dx + dy * dy);
    // One control point off to the side gives the arc; the side flips at random
    // so two moves in a row never trace the same line.
    var bow = (dist * 0.18 + 8) * (Math.random() < 0.5 ? -1 : 1);
    var cx = sx + dx / 2 - (dy / (dist || 1)) * bow;
    var cy = sy + dy / 2 + (dx / (dist || 1)) * bow;
    var token = {};
    moving = token;
    var t0 = 0;
    return new Promise(function (done) {
      function frame(now) {
        if (moving !== token) return done(false);
        if (!t0) t0 = now;
        var p = Math.min(1, (now - t0) / ms);
        var e = easeInOut(p);
        var inv = 1 - e;
        // quadratic bezier through the control point
        var px = inv * inv * sx + 2 * inv * e * cx + e * e * tx;
        var py = inv * inv * sy + 2 * inv * e * cy + e * e * ty;
        // a little hand-shake, fading out as it lands
        var wob = (1 - e) * 1.6;
        x = px + (Math.random() - 0.5) * wob;
        y = py + (Math.random() - 0.5) * wob;
        place();
        if (p < 1) return root.requestAnimationFrame(frame);
        x = tx;
        y = ty;
        place();
        moving = null;
        done(true);
      }
      root.requestAnimationFrame(frame);
    });
  }

  function press() {
    attach();
    if (dot) {
      dot.style.transform = "scale(.62)";
      root.setTimeout(function () {
        if (dot) dot.style.transform = "scale(1)";
      }, 110);
    }
    if (node) {
      var r = document.createElement("div");
      r.className = "ripple";
      node.appendChild(r);
      root.setTimeout(function () {
        if (r.parentNode) r.parentNode.removeChild(r);
      }, 450);
    }
    return Promise.resolve(true);
  }

  /** dwell keeps it alive: a tiny drift so it never looks frozen. */
  function breathe(ms) {
    var t0 = Date.now();
    return new Promise(function (done) {
      (function step() {
        if (Date.now() - t0 >= ms) return done(true);
        x += (Math.random() - 0.5) * 0.7;
        y += (Math.random() - 0.5) * 0.7;
        place();
        root.setTimeout(step, 90);
      })();
    });
  }

  O.cursor = {
    mount: function () {
      if (document.body) {
        attach();
        watch();
      } else {
        document.addEventListener("DOMContentLoaded", function () {
          attach();
          watch();
        });
      }
      if (!x && !y) {
        x = Math.round((root.innerWidth || 390) / 2);
        y = Math.round((root.innerHeight || 844) * 0.62);
        place();
      }
      return true;
    },
    moveTo: moveTo,
    press: press,
    breathe: breathe,
    at: function () {
      return { x: x, y: y };
    },
    setName: function (n) {
      O.cursorName = String(n || "Bea");
      if (label) label.textContent = O.cursorName;
    },
    el: function () {
      return node;
    },
  };
})(window);

/* ---- agent/sites/common.js ---- */
/**
 * sites/common.js — the finders every recipe is built out of.
 *
 * Role, aria-label, visible text. Never a generated class name. Every finder
 * returns null when it finds nothing, so a recipe can say "I could not find
 * the like button" instead of pressing whatever happened to be nearby.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.find) return;
  O.sites = O.sites || {};

  function visible(el) {
    if (!el || !el.getBoundingClientRect) return false;
    var r = el.getBoundingClientRect();
    if (r.width < 2 || r.height < 2) return false;
    var st = root.getComputedStyle ? root.getComputedStyle(el) : null;
    if (st && (st.visibility === "hidden" || st.display === "none" || st.opacity === "0"))
      return false;
    return true;
  }

  function all(sel, scope) {
    return Array.prototype.slice.call((scope || document).querySelectorAll(sel));
  }

  /** Elements whose aria-label matches, exactly or by a regexp. */
  function byLabel(match, scope) {
    var test =
      match instanceof RegExp
        ? function (v) {
            return match.test(v);
          }
        : function (v) {
            return v.toLowerCase() === String(match).toLowerCase();
          };
    return all("[aria-label]", scope).filter(function (el) {
      return test((el.getAttribute("aria-label") || "").trim()) && visible(el);
    });
  }

  function oneByLabel(match, scope) {
    var hits = byLabel(match, scope);
    return hits.length ? hits[0] : null;
  }

  /** Elements with an explicit or implicit role. */
  function byRole(role, scope) {
    var implicit = { button: "button", link: "a[href]", textbox: "input,textarea" }[role] || "";
    var sel = '[role="' + role + '"]' + (implicit ? "," + implicit : "");
    return all(sel, scope).filter(visible);
  }

  /** The first element of a role whose visible text matches. */
  function byText(role, match, scope) {
    var test =
      match instanceof RegExp
        ? function (v) {
            return match.test(v);
          }
        : function (v) {
            return v.toLowerCase().indexOf(String(match).toLowerCase()) >= 0;
          };
    var hits = byRole(role, scope).filter(function (el) {
      return test(((el.innerText || el.textContent || "") + "").replace(/\s+/g, " ").trim());
    });
    return hits.length ? hits[0] : null;
  }

  /** A text field: role=textbox, contenteditable, or a labelled input. */
  function field(match, scope) {
    var labelled = byLabel(match, scope).filter(function (el) {
      return (
        el.tagName === "INPUT" ||
        el.tagName === "TEXTAREA" ||
        el.isContentEditable ||
        el.getAttribute("role") === "textbox"
      );
    });
    if (labelled.length) return labelled[0];
    var ph = all("input[placeholder],textarea[placeholder]", scope).filter(function (el) {
      var p = el.getAttribute("placeholder") || "";
      return (match instanceof RegExp ? match.test(p) : p.toLowerCase().indexOf(String(match).toLowerCase()) >= 0) && visible(el);
    });
    if (ph.length) return ph[0];
    var ce = all('[contenteditable="true"],[role="textbox"]', scope).filter(visible);
    return ce.length ? ce[0] : null;
  }

  /** The nearest ancestor that behaves like a button (for an icon inside one). */
  function clickable(el) {
    var n = el;
    for (var i = 0; n && i < 6; i++, n = n.parentElement) {
      if (!n.tagName) continue;
      if (n.tagName === "BUTTON" || n.getAttribute("role") === "button" || n.tagName === "A")
        return n;
    }
    return el;
  }

  O.find = {
    visible: visible,
    all: all,
    byLabel: byLabel,
    oneByLabel: oneByLabel,
    byRole: byRole,
    byText: byText,
    field: field,
    clickable: clickable,
  };
})(window);

/* ---- agent/sites/instagram.js ---- */
/**
 * sites/instagram.js — where things are on mobile Instagram.
 *
 * Found by aria-label, role and visible text only. Instagram's class names are
 * generated and change without notice, so none appear here.
 *
 * WHEN A SELECTOR IS NOT FOUND: every function below returns null (or false),
 * and returns it immediately rather than falling back to a guess. The brain
 * treats null as "the page is not what I thought" and either waits, re-reads,
 * or stops — it never presses something it did not identify.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  O.sites = O.sites || {};
  if (O.sites.instagram) return;
  var F = O.find;

  O.sites.instagram = {
    name: "instagram",

    /** The like control of a post (or of the post under the cursor). null if absent. */
    likeButton: function (scope) {
      var el = F.oneByLabel(/^like$/i, scope);
      if (!el) el = F.oneByLabel(/^unlike$/i, scope); // already liked: still the control
      return el ? F.clickable(el) : null;
    },

    liked: function (scope) {
      return !!F.oneByLabel(/^unlike$/i, scope);
    },

    /** The comment field. null when the composer is not open. */
    commentBox: function (scope) {
      return F.field(/comment/i, scope);
    },

    /** The first reel link on screen; null on a page with no reels. */
    openReel: function () {
      var a = F.all('a[href*="/reel/"]').filter(F.visible)[0];
      return a || null;
    },

    /** Mobile reels advance by scrolling one viewport. Nothing to click. */
    nextReel: function () {
      return { kind: "scroll", px: root.innerHeight || 844 };
    },

    /** Our own profile URL, from the handle. null when the handle is unreadable. */
    profileUrl: function () {
      var h = this.handle();
      return h ? "https://www.instagram.com/" + h + "/" : null;
    },

    /** The thing to press to get to our own profile. null when not on screen. */
    profileLink: function () {
      var el = O.find.oneByLabel(/^profile$/i);
      return el ? O.find.clickable(el) : null;
    },

    isLoginPage: function () {
      if (/\/accounts\/(login|emailsignup)/.test(location.pathname)) return true;
      var pw = document.querySelector('input[type="password"]');
      if (pw && F.visible(pw)) return true;
      return !!F.byText("button", /^log in$/i);
    },

    signedIn: function () {
      if (this.isLoginPage()) return false;
      return !!(
        F.oneByLabel(/^(home|profile|new post|search)$/i) ||
        document.querySelector('a[href="/direct/inbox/"]')
      );
    },

    /**
     * The signed-in handle, asked of Instagram itself: the current-user
     * endpoint first, then the viewer JSON the page embeds, then the profile
     * link in the tab bar. Every step returns null rather than a guess, and
     * the whole chain resolves null off instagram.com (the fetch is
     * same-origin only).
     */
    handleAsync: function () {
      var self = this;
      var viaDom = function () {
        return self.handle();
      };
      if (!/instagram\./.test(location.hostname) || typeof fetch !== "function")
        return Promise.resolve(viaDom());
      return fetch("/api/v1/accounts/current_user/?edit=true", {
        credentials: "include",
        headers: { "x-ig-app-id": "936619743392459" },
      })
        .then(function (r) {
          if (!r.ok) throw new Error("http " + r.status);
          return r.json();
        })
        .then(function (j) {
          var u = j && j.user && j.user.username;
          if (u) return u;
          throw new Error("no username");
        })
        .catch(function () {
          // the viewer blob the page ships with, when the endpoint says no
          var m = /"viewer":\{[^}]*?"username":"([A-Za-z0-9._]{2,30})"/.exec(
            document.documentElement.innerHTML,
          );
          return m ? m[1] : viaDom();
        });
    },

    /** The handle as the DOM shows it: the profile link in the tab bar. */
    handle: function () {
      var prof = F.oneByLabel(/^profile$/i);
      var a = prof && (prof.tagName === "A" ? prof : prof.closest && prof.closest("a[href]"));
      if (a) {
        var m = /^\/([A-Za-z0-9._]{2,30})\/?$/.exec(a.getAttribute("href") || "");
        if (m) return m[1];
      }
      var m2 = /^\/([A-Za-z0-9._]{2,30})\/?$/.exec(location.pathname);
      if (m2 && document.querySelector('[aria-label="Edit profile"], a[href*="/accounts/edit"]'))
        return m2[1];
      return null;
    },

    postNodes: function () {
      return F.all("article").filter(F.visible);
    },

    captionOf: function (el) {
      // a caption is a leaf, or a paragraph whose only children are its own
      // hashtag links — anything deeper is layout, not words
      var spans = F.all("h1, h2, span, p", el).filter(function (n) {
        if (!n.children.length) return true;
        for (var i = 0; i < n.children.length; i++)
          if (n.children[i].tagName !== "A") return false;
        return true;
      });
      var best = null;
      for (var i = 0; i < spans.length; i++) {
        var t = (spans[i].innerText || spans[i].textContent || "").replace(/\s+/g, " ").trim();
        if (t.length < 8) continue;
        if (/^\d[\d.,]*\s*[KMB]?\s*(likes?|views?|comments?)$/i.test(t)) continue;
        if (!best || t.length > best.length) best = t;
      }
      return best;
    },
  };
})(window);

/* ---- agent/sites/tiktok.js ---- */
/**
 * sites/tiktok.js — where things are on mobile TikTok.
 *
 * Role, aria-label and visible text only. TikTok's data-e2e hooks are stable
 * enough to use as a second opinion, but never a generated class name.
 *
 * WHEN A SELECTOR IS NOT FOUND: null, immediately, with no fallback guess. The
 * brain decides what to do with a null — it is never treated as "press the
 * nearest thing".
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  O.sites = O.sites || {};
  if (O.sites.tiktok) return;
  var F = O.find;

  O.sites.tiktok = {
    name: "tiktok",

    likeButton: function (scope) {
      var el = F.oneByLabel(/^(like|unlike)$/i, scope);
      if (!el) el = F.byText("button", /^like$/i, scope);
      if (!el) {
        var hook = (scope || document).querySelector('[data-e2e="like-icon"]');
        if (hook && F.visible(hook)) el = hook;
      }
      return el ? F.clickable(el) : null;
    },

    liked: function (scope) {
      var el = F.oneByLabel(/^unlike$/i, scope);
      return !!el;
    },

    commentBox: function (scope) {
      return F.field(/(add comment|comment)/i, scope);
    },

    /** The video under the cursor; on the For You page there is always one. */
    openReel: function () {
      var a = F.all('a[href*="/video/"]').filter(F.visible)[0];
      return a || null;
    },

    nextReel: function () {
      return { kind: "scroll", px: root.innerHeight || 844 };
    },

    profileUrl: function () {
      var h = this.handle();
      return h ? "https://www.tiktok.com/@" + h : null;
    },

    profileLink: function () {
      var el =
        document.querySelector('[data-e2e="profile-icon"]') || O.find.oneByLabel(/^profile$/i);
      return el && O.find.visible(el) ? O.find.clickable(el) : null;
    },

    isLoginPage: function () {
      if (/\/login/.test(location.pathname)) return true;
      var pw = document.querySelector('input[type="password"]');
      if (pw && F.visible(pw)) return true;
      return !!F.byText("button", /^log in$/i);
    },

    signedIn: function () {
      if (this.isLoginPage()) return false;
      return !!(
        document.querySelector('[data-e2e="profile-icon"]') ||
        F.oneByLabel(/^(profile|inbox|upload)$/i)
      );
    },

    handle: function () {
      var a = F.all('a[href^="/@"]').filter(function (n) {
        return /^\/@[A-Za-z0-9._]{2,30}\/?$/.test(n.getAttribute("href") || "");
      })[0];
      if (a) return a.getAttribute("href").slice(2).replace(/\/$/, "");
      var m = /^\/@([A-Za-z0-9._]{2,30})/.exec(location.pathname);
      if (m && document.querySelector('[data-e2e="edit-profile"], [aria-label="Edit profile"]'))
        return m[1];
      return null;
    },

    postNodes: function () {
      var byHook = F.all('[data-e2e="recommend-list-item-container"]').filter(F.visible);
      if (byHook.length) return byHook;
      return F.all('article, [role="article"]').filter(F.visible);
    },

    captionOf: function (el) {
      var n = el.querySelector('[data-e2e="video-desc"]');
      if (n) return (n.innerText || n.textContent || "").replace(/\s+/g, " ").trim();
      return null; // not found: let read.js fall back, or report nothing
    },
  };
})(window);

/* ---- agent/sites/youtube.js ---- */
/**
 * sites/youtube.js — only as much as the brain asks for: is this account
 * signed in, and what is its handle.
 *
 * The handle is a channel handle and NEVER an email address. That bug shipped
 * once: the account page prints "Signed in as alex@gmail.com" right next to
 * the channel name, and the reader took the mailbox. Anything with an "@"
 * inside it, or a mail-shaped ending, is refused here and again in read.js.
 *
 * WHEN A SELECTOR IS NOT FOUND: null. No fallback guess.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  O.sites = O.sites || {};
  if (O.sites.youtube) return;
  var F = O.find;

  var MAILISH = /@|\.(com|net|org|co)$/i;

  O.sites.youtube = {
    name: "youtube",

    likeButton: function (scope) {
      var el = F.oneByLabel(/^(like this video|like|unlike)/i, scope);
      return el ? F.clickable(el) : null;
    },

    liked: function (scope) {
      var el = F.oneByLabel(/^(unlike|like this video)/i, scope);
      return !!(el && el.getAttribute("aria-pressed") === "true");
    },

    commentBox: function (scope) {
      return F.field(/comment/i, scope);
    },

    openReel: function () {
      var a = F.all('a[href*="/shorts/"]').filter(F.visible)[0];
      return a || null;
    },

    nextReel: function () {
      return { kind: "scroll", px: root.innerHeight || 844 };
    },

    profileUrl: function () {
      var h = this.handle();
      return h ? "https://www.youtube.com/@" + h : null;
    },

    profileLink: function () {
      var el = F.oneByLabel(/^(your channel|account menu|avatar)/i);
      return el ? F.clickable(el) : null;
    },

    isLoginPage: function () {
      if (/accounts\.google\./.test(location.hostname)) return true;
      var pw = document.querySelector('input[type="password"]');
      if (pw && F.visible(pw)) return true;
      return !!F.byText("link", /^sign in$/i);
    },

    signedIn: function () {
      if (this.isLoginPage()) return false;
      return !!(
        F.oneByLabel(/^(account menu|your channel|create)/i) ||
        document.querySelector("#avatar-btn")
      );
    },

    handle: function () {
      var a = F.all('a[href^="/@"], a[href*="youtube.com/@"]').filter(function (n) {
        return /\/@[A-Za-z0-9._-]{2,30}\/?$/.test(n.getAttribute("href") || "");
      })[0];
      if (a) {
        var m = /\/@([A-Za-z0-9._-]{2,30})/.exec(a.getAttribute("href"));
        if (m && !MAILISH.test(m[1])) return m[1];
      }
      var t = (document.body && (document.body.innerText || "")) || "";
      var h = /(^|\s)@([A-Za-z0-9._-]{3,30})(\s|$)/.exec(t);
      if (h && !MAILISH.test(h[2])) return h[2];
      return null; // a mailbox is not a handle
    },

    postNodes: function () {
      return F.all('ytd-rich-item-renderer, [role="article"], article').filter(F.visible);
    },

    captionOf: function (el) {
      var n = el.querySelector("#video-title, h3, a[title]");
      if (!n) return null;
      return (n.getAttribute("title") || n.innerText || n.textContent || "").replace(/\s+/g, " ").trim();
    },
  };
})(window);

/* ---- agent/read.js ---- */
/**
 * read.js — reading the page for the crew.
 *
 * Everything here is found by role, aria-label and visible text. Never by a
 * generated class name, because those change weekly. When something is not
 * found this returns null or an empty list — it never guesses.
 *
 * It reads no input values at all. The one field the agent ever reads back is
 * the comment box hands.type() just wrote to, and that read lives there.
 *
 * The brain asks for exactly these: signedIn, handle, text, posts, tags, ads,
 * store.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.read) return;

  function text(el) {
    if (!el) return "";
    return (el.innerText || el.textContent || "").replace(/\s+/g, " ").trim();
  }

  function platform() {
    var h = location.hostname || "";
    if (/instagram\./.test(h)) return "instagram";
    if (/tiktok\./.test(h)) return "tiktok";
    if (/youtube\./.test(h)) return "youtube";
    return "unknown";
  }

  function site(which) {
    var p = which || platform();
    return (O.sites && O.sites[p]) || null;
  }

  /** Signed in when the platform recipe says so; unknown platform => false. */
  function signedIn(which) {
    var s = site(which);
    if (!s) return false;
    if (s.isLoginPage()) return false;
    return !!s.signedIn();
  }

  /**
   * Our own handle as "@name", or null. A connection with no readable handle
   * is not a connection. Async, because Instagram's best answer is a fetch.
   */
  function handle(which) {
    var s = site(which);
    if (!s) return Promise.resolve(null);
    var got = s.handleAsync ? s.handleAsync() : Promise.resolve(s.handle());
    return Promise.resolve(got)
      .then(function (h) {
        if (!h) return null;
        h = String(h).trim().replace(/^@+/, "");
        // never an email address — that bug shipped once on YouTube
        if (!h || h.indexOf("@") >= 0 || /\.(com|net|org|co)$/i.test(h)) return null;
        if (!/^[A-Za-z0-9._-]{2,40}$/.test(h)) return null;
        return "@" + h;
      })
      .catch(function () {
        return null;
      });
  }

  /** The first ~4000 characters the page shows. The brain looks for friction. */
  function bodyText(max) {
    var b = document.body;
    if (!b) return "";
    var t = b.innerText || b.textContent || "";
    return t.slice(0, max || 4000);
  }

  var NUM = /([\d][\d.,]*)\s*([KMB])?\s*(likes?|views?|plays?|comments?)/i;

  function countsIn(el) {
    var out = {};
    var take = function (m) {
      if (!m) return;
      var n = parseFloat(m[1].replace(/,/g, ""));
      var mult = { K: 1e3, M: 1e6, B: 1e9 }[(m[2] || "").toUpperCase()] || 1;
      var kind = m[3].toLowerCase().replace(/s$/, "");
      if (kind === "play") kind = "view";
      if (out[kind] == null) out[kind] = Math.round(n * mult);
    };
    var re = new RegExp(NUM.source, "gi");
    var t = text(el);
    var m;
    while ((m = re.exec(t))) take(m);
    var labelled = el.querySelectorAll("[aria-label]");
    for (var i = 0; i < labelled.length; i++) take(NUM.exec(labelled[i].getAttribute("aria-label") || ""));
    return out;
  }

  function handleIn(el) {
    var links = el.querySelectorAll('a[href^="/@"], a[href*="/@"]');
    for (var i = 0; i < links.length; i++) {
      var m = /\/@([A-Za-z0-9._]+)/.exec(links[i].getAttribute("href") || "");
      if (m) return "@" + m[1];
    }
    var m2 = /@([A-Za-z0-9._]{2,30})/.exec(text(el));
    if (m2) return "@" + m2[1];
    var byRole = el.querySelector("a[href]");
    if (byRole) {
      var m3 = /^\/([A-Za-z0-9._]{2,30})\/?$/.exec(byRole.getAttribute("href") || "");
      if (m3) return "@" + m3[1];
    }
    return null;
  }

  function abs(href) {
    try {
      return new URL(href, location.href).href;
    } catch (e) {
      return href || null;
    }
  }

  function urlIn(el) {
    var a =
      el.querySelector('a[href*="/reel/"], a[href*="/p/"], a[href*="/video/"], a[href*="/shorts/"]') ||
      el.querySelector("a[href]");
    return a ? abs(a.getAttribute("href")) : null;
  }

  /** Posts on screen: {url, handle, views, ...}. Deduped by url, at most 40. */
  function posts() {
    var s = site();
    var nodes = (s && s.postNodes && s.postNodes()) || [];
    if (!nodes.length) nodes = Array.prototype.slice.call(document.querySelectorAll("article"));
    if (!nodes.length)
      nodes = Array.prototype.slice.call(document.querySelectorAll('[role="article"]'));
    var seen = Object.create(null);
    var out = [];
    for (var i = 0; i < nodes.length && out.length < 40; i++) {
      var el = nodes[i];
      var c = countsIn(el);
      var url = urlIn(el);
      var h = handleIn(el);
      var key = url || (h || "") + "#" + i;
      if (seen[key]) continue;
      seen[key] = 1;
      out.push({
        url: url,
        handle: h,
        views: c.view == null ? null : c.view,
        likes: c.like == null ? null : c.like,
        comments: c.comment == null ? null : c.comment,
        caption: captionOf(el),
      });
    }
    return out;
  }

  /**
   * The hashtags this page carries: the ones the platform itself links
   * (/explore/tags/x/, /tag/x) plus #word in the captions. Most-seen first,
   * at most 20.
   */
  function tags(scope) {
    var root_ = scope || document.body || document.documentElement;
    if (!root_) return [];
    var count = Object.create(null);
    var order = [];
    var push = function (t) {
      var v = "#" + String(t).replace(/^#/, "").toLowerCase();
      if (!/^#[a-z0-9_]{2,60}$/.test(v)) return;
      if (count[v] == null) {
        count[v] = 0;
        order.push(v);
      }
      count[v]++;
    };
    var links = root_.querySelectorAll('a[href*="/explore/tags/"], a[href*="/tag/"]');
    for (var i = 0; i < links.length; i++) {
      var href = links[i].getAttribute("href") || "";
      var m = /\/(?:explore\/tags|tag)\/([^/?#]+)/.exec(href);
      if (m) push(decodeURIComponent(m[1]));
      else {
        var t = text(links[i]);
        if (/^#/.test(t)) push(t);
      }
    }
    var re = /#[A-Za-z0-9_]{2,60}/g;
    var body = text(root_);
    var mm;
    while ((mm = re.exec(body))) push(mm[0]);
    order.sort(function (a, b) {
      return count[b] - count[a];
    });
    return order.slice(0, 20);
  }

  /** The caption of a post element: the recipe knows, otherwise longest text. */
  function captionOf(el) {
    if (!el) return null;
    var s = site();
    if (s && s.captionOf) {
      var viaSite = s.captionOf(el);
      if (viaSite != null) return viaSite;
    }
    var best = null;
    var cands = el.querySelectorAll("p, h1, h2, span, div");
    for (var i = 0; i < cands.length; i++) {
      if (cands[i].children.length) continue; // leaves only
      var t = text(cands[i]);
      if (t.length < 8) continue;
      if (NUM.test(t)) continue;
      if (!best || t.length > best.length) best = t;
    }
    return best;
  }

  /**
   * The Meta Ad Library, read off the visible cards.
   * `started` is the date exactly as printed ("Started running on Aug 2, 2026"
   * gives "Aug 2, 2026"). A card with no advertiser is skipped rather than
   * guessed at.
   */
  function ads() {
    var cards = Array.prototype.slice.call(
      document.querySelectorAll('[role="article"], article, [data-testid*="ad" i]'),
    );
    if (!cards.length) {
      // the library also renders each result as a plain block with the
      // "Library ID" line in it; take those blocks' nearest sized ancestor
      var ids = Array.prototype.slice.call(document.querySelectorAll("div,section")).filter(function (n) {
        return !n.querySelector("div,section") && /Library ID/i.test(text(n));
      });
      cards = ids
        .map(function (n) {
          var p = n;
          for (var i = 0; i < 4 && p.parentElement; i++) p = p.parentElement;
          return p;
        })
        .filter(Boolean);
    }
    var seen = Object.create(null);
    var out = [];
    for (var i = 0; i < cards.length && out.length < 40; i++) {
      var el = cards[i];
      var t = text(el);
      if (!/Library ID|Started running|Sponsored/i.test(t)) continue;
      var startedM = /Started running on\s+([A-Za-z]{3,9}\s+\d{1,2},\s+\d{4})/.exec(t);
      var link = el.querySelector('a[href*="http"], a[href^="/"]');
      var name = null;
      var nameEl = el.querySelector("a[href] span, a[href] strong, a[href]");
      if (nameEl) name = text(nameEl);
      if (!name) {
        var m = /Sponsored\s*·?\s*([^\n·]{2,60})/.exec(t);
        if (m) name = m[1].trim();
      }
      if (!name) continue; // no advertiser: skip, do not guess
      var body = t
        .replace(/Started running on\s+[A-Za-z]{3,9}\s+\d{1,2},\s+\d{4}/i, " ")
        .replace(/Library ID:?\s*\d+/i, " ")
        .replace(/Sponsored/i, " ")
        .replace(name, " ")
        .replace(/\s+/g, " ")
        .trim();
      var url = link ? abs(link.getAttribute("href")) : null;
      var key = name + "|" + (startedM ? startedM[1] : "") + "|" + body.slice(0, 60);
      if (seen[key]) continue;
      seen[key] = 1;
      out.push({
        advertiser: name,
        started: startedM ? startedM[1] : null,
        text: body.slice(0, 600),
        url: url,
      });
    }
    return out;
  }

  /**
   * Our own storefront, walked the way a visitor walks it — the logic that
   * used to live in worker/store.mjs, moved in here because the page is the
   * only thing with a browser now.
   *
   * Same origin only: the agent can fetch the store's own pages when the web
   * view is already on the store (the brain sends `goto` first). From another
   * origin the browser would refuse the fetch, so this says so plainly rather
   * than returning an empty shop.
   *
   * The dedupe trap from store.mjs is kept: ?variant=… is the same product in
   * another colour, so links are keyed by pathname with search and hash gone.
   */
  var PRODUCT_PATH = /\/(products?|product|item|items|p|shop)\/[^/?#]+/i;
  var LISTING_PATH = /\/(collections?|categories?|category|shop|products|all)(\/[^/?#]+)?\/?$/i;

  function linksIn(doc, base) {
    var here = new URL(base).host;
    var seen = Object.create(null);
    var products = [];
    var listings = [];
    var as = doc.querySelectorAll("a[href]");
    for (var i = 0; i < as.length; i++) {
      var u;
      try {
        u = new URL(as[i].getAttribute("href"), base);
      } catch (e) {
        continue;
      }
      if (u.host !== here) continue;
      u.hash = "";
      u.search = "";
      if (seen[u.href]) continue;
      seen[u.href] = 1;
      if (PRODUCT_PATH.test(u.pathname)) products.push(u.href);
      else if (LISTING_PATH.test(u.pathname)) listings.push(u.href);
    }
    return { products: products, listings: listings };
  }

  function productFrom(doc, url) {
    var meta = function (sel) {
      var n = doc.querySelector(sel);
      var v = n && n.getAttribute("content");
      return v ? v.trim() : null;
    };
    var title = meta('meta[property="og:title"]');
    if (!title) {
      var h1 = doc.querySelector("h1");
      title = h1 ? text(h1) : null;
    }
    if (!title) title = doc.title || null;
    var image = meta('meta[property="og:image"]');
    if (!image) {
      var img = doc.querySelector("main img, img");
      image = img ? abs(img.getAttribute("src")) : null;
    }
    var price =
      meta('meta[property="product:price:amount"]') || meta('meta[property="og:price:amount"]');
    if (!price) {
      var ip = doc.querySelector('[itemprop="price"]');
      price = (ip && (ip.getAttribute("content") || text(ip))) || null;
    }
    if (!price) {
      var scope = doc.body || doc.documentElement;
      var pm = /(?:[$€£]\s?\d[\d,]*(?:\.\d{2})?|\d[\d,]*(?:\.\d{2})?\s?(?:USD|EUR|GBP))/.exec(
        text(scope),
      );
      price = pm ? pm[0] : null;
    }
    return {
      url: url,
      title: title ? String(title).trim() : null,
      price: price ? String(price).trim() : null,
      image: image,
    };
  }

  function fetchDoc(url) {
    return root
      .fetch(url, { credentials: "same-origin" })
      .then(function (r) {
        if (!r.ok) throw new Error("http " + r.status);
        return r.text();
      })
      .then(function (html) {
        return new root.DOMParser().parseFromString(html, "text/html");
      });
  }

  function store(url, opts) {
    opts = opts || {};
    var limit = opts.limit || 30;
    if (!url) return Promise.resolve({ products: [], stopped: "no store url" });
    var base;
    try {
      base = new URL(url, location.href);
    } catch (e) {
      return Promise.resolve({ products: [], stopped: "the store url is not a url" });
    }
    if (base.origin !== location.origin)
      return Promise.resolve({
        products: [],
        stopped: "not on the store — open " + base.origin + " first",
      });

    return fetchDoc(base.href)
      .then(function (doc) {
        var found = linksIn(doc, base.href);
        var chain = Promise.resolve(found.products.slice());
        found.listings.slice(0, 3).forEach(function (listing) {
          chain = chain.then(function (acc) {
            if (acc.length >= limit) return acc;
            return fetchDoc(listing)
              .then(function (d2) {
                var more = linksIn(d2, listing).products;
                more.forEach(function (p) {
                  if (acc.indexOf(p) < 0) acc.push(p);
                });
                return acc;
              })
              .catch(function () {
                return acc;
              });
          });
        });
        return chain;
      })
      .then(function (links) {
        links = links.slice(0, limit);
        var products = [];
        var chain = Promise.resolve();
        links.forEach(function (link) {
          chain = chain.then(function () {
            return fetchDoc(link)
              .then(function (d) {
                var p = productFrom(d, link);
                if (p.title) products.push(p);
              })
              .catch(function () {});
          });
        });
        return chain.then(function () {
          if (!products.length)
            return {
              products: products,
              stopped: links.length
                ? "the product pages did not read"
                : "no products found on the store",
            };
          return { products: products, stopped: null };
        });
      })
      .catch(function (e) {
        return { products: [], stopped: "the store did not open: " + ((e && e.message) || e) };
      });
  }

  O.read = {
    platform: platform,
    signedIn: signedIn,
    handle: handle,
    bodyText: bodyText,
    posts: posts,
    tags: tags,
    ads: ads,
    store: store,
    captionOf: captionOf,
    text: text,
  };
})(window);

/* ---- agent/hands.js ---- */
/**
 * hands.js — scroll, tap, type, dwell.
 *
 * Nothing in this file decides WHEN to act. The brain decides; the hands
 * execute. Every action moves the cursor to the target first and waits a beat,
 * because that beat is the whole point: Alex is watching the wand move.
 *
 * Honest note about taps: events synthesised from a script always carry
 * isTrusted === false. There is no way to forge that from page JS — only the
 * user or the browser engine can. React and most sites listen for the event
 * pair anyway, so the sequence below works; where a site checks isTrusted, the
 * tap will not take, and tapEl reports back that nothing changed instead of
 * pretending it worked. el.click() is kept as a fallback for exactly that case
 * — see sig() for why it is not fired unconditionally.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.hands) return;

  var stopped = false;
  var sleep = function (ms) {
    return new Promise(function (r) {
      root.setTimeout(r, ms);
    });
  };

  function centerOf(el) {
    var r = el.getBoundingClientRect();
    return { x: r.left + r.width / 2, y: r.top + r.height / 2 };
  }

  function inView(el) {
    var r = el.getBoundingClientRect();
    var h = root.innerHeight || 844;
    return r.bottom > 8 && r.top < h - 8;
  }

  /**
   * scroll(px, {pace}) — human bursts with pauses, window.scrollBy in small
   * steps. Never scrollTo, never one jump.
   */
  function scroll(px, opts) {
    opts = opts || {};
    // the brain's paces: "read" is a slow browse, "skim" is a fast flick
    var pace = opts.pace || "easy";
    var perStep = pace === "skim" || pace === "fast" ? 34 : pace === "read" || pace === "slow" ? 12 : 22;
    var burst = pace === "skim" || pace === "fast" ? 9 : pace === "read" || pace === "slow" ? 4 : 6;
    var dir = px < 0 ? -1 : 1;
    var left = Math.abs(px);
    var steps = 0;
    return new Promise(function (done) {
      (function bursts() {
        if (stopped || left <= 0) return done({ moved: true, steps: steps });
        var n = 0;
        (function step() {
          if (stopped || left <= 0 || n >= burst) {
            if (stopped || left <= 0) return done({ moved: true, steps: steps });
            return sleep(160 + Math.random() * 260).then(bursts);
          }
          var amt = Math.min(left, perStep + Math.round(Math.random() * 8));
          root.scrollBy(0, dir * amt);
          left -= amt;
          n++;
          steps++;
          root.setTimeout(step, 16);
        })();
      })();
    });
  }

  function fire(el, type, pt, extra) {
    var Ctor =
      type.indexOf("pointer") === 0 && root.PointerEvent ? root.PointerEvent : root.MouseEvent;
    var init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      view: root,
      clientX: pt.x,
      clientY: pt.y,
      screenX: pt.x,
      screenY: pt.y,
      button: 0,
      buttons: type === "pointerdown" || type === "mousedown" ? 1 : 0,
      detail: 1,
    };
    if (Ctor === root.PointerEvent) {
      init.pointerId = 1;
      init.pointerType = "touch";
      init.isPrimary = true;
      init.width = 1;
      init.height = 1;
      init.pressure = init.buttons ? 0.5 : 0;
    }
    if (extra) for (var k in extra) init[k] = extra[k];
    try {
      el.dispatchEvent(new Ctor(type, init));
    } catch (e) {
      /* a page that has broken the constructor is not worth crashing over */
    }
  }

  /**
   * A cheap signature of "did this control change state". Dispatching the
   * sequence AND calling el.click() would press a toggle twice — like, then
   * unlike — so el.click() is the fallback only: it runs when the dispatched
   * click changed nothing, which is the case on a site that ignores untrusted
   * events, and is skipped when the sequence already took.
   */
  function sig(el) {
    if (!el || !el.isConnected) return null;
    return (
      (el.getAttribute("aria-label") || "") +
      "|" + (el.getAttribute("aria-pressed") || "") +
      "|" + (el.getAttribute("aria-selected") || "") +
      "|" + ((el.innerText || el.textContent || "").slice(0, 40))
    );
  }

  var SEQ = [
    "pointerover",
    "pointerenter",
    "pointerdown",
    "mousedown",
    "pointerup",
    "mouseup",
    "click",
  ];

  function tapAt(px, py, opts) {
    opts = opts || {};
    return O.cursor.moveTo(px, py, { ms: opts.ms || 480 }).then(function () {
      return sleep(90 + Math.random() * 180);
    }).then(function () {
      return O.cursor.press();
    }).then(function () {
      var pt = { x: px, y: py };
      var target = document.elementFromPoint(px, py) || document.body;
      var before = target ? target.getAttribute("aria-label") : null;
      var s0 = sig(target);
      SEQ.forEach(function (t) {
        fire(target, t, pt);
      });
      if (target && target.isConnected && sig(target) === s0 && typeof target.click === "function") {
        try {
          target.click();
        } catch (e) {
          /* ignore */
        }
      }
      return {
        hit: !!target,
        stillThere: !!(target && target.isConnected),
        labelBefore: before,
        labelAfter: target && target.isConnected ? target.getAttribute("aria-label") : null,
        changed: !!(target && target.isConnected && target.getAttribute("aria-label") !== before),
      };
    });
  }

  function tapEl(el, opts) {
    if (!el) return Promise.resolve({ hit: false, stillThere: false, changed: false });
    var pre = Promise.resolve();
    if (!inView(el)) {
      // bring it on screen the way a thumb would, not with scrollIntoView
      var r = el.getBoundingClientRect();
      pre = scroll(Math.round(r.top - (root.innerHeight || 844) * 0.45), { pace: "easy" });
    }
    return pre.then(function () {
      var c = centerOf(el);
      var before = el.getAttribute("aria-label");
      return O.cursor
        .moveTo(c.x, c.y, { ms: (opts && opts.ms) || 520 })
        .then(function () {
          return sleep(90 + Math.random() * 200);
        })
        .then(function () {
          return O.cursor.press();
        })
        .then(function () {
          var pt = centerOf(el);
          var under = document.elementFromPoint(pt.x, pt.y);
          var target = under && el.contains(under) ? under : el;
          var s0 = sig(el);
          SEQ.forEach(function (t) {
            fire(target, t, pt);
          });
          if (el.isConnected && sig(el) === s0 && typeof el.click === "function") {
            try {
              el.click();
            } catch (e) {
              /* ignore */
            }
          }
          return sleep(60);
        })
        .then(function () {
          var after = el.isConnected ? el.getAttribute("aria-label") : null;
          return {
            hit: true,
            stillThere: !!el.isConnected,
            labelBefore: before,
            labelAfter: after,
            changed: after !== before,
          };
        });
    });
  }

  /** The native value setter, so React's own onChange sees the write. */
  function setValue(el, v) {
    var proto =
      el instanceof root.HTMLTextAreaElement
        ? root.HTMLTextAreaElement.prototype
        : root.HTMLInputElement.prototype;
    var desc = Object.getOwnPropertyDescriptor(proto, "value");
    if (desc && desc.set) desc.set.call(el, v);
    else el.value = v;
  }

  /**
   * type(text, {into, strokes, delays, typos})
   *
   * `strokes` is what the brain actually sends: [{key, delayMs}], where a key
   * of "\b" is a backspace. The strokes ARE the rhythm — they are played back
   * exactly, and nothing here invents timing of its own.
   * `delays` + `typos` are the older, simpler form and are turned into the
   * same strokes: one ms per character (a short array repeats its last value),
   * and {at, ch} for a wrong character typed at that index then backspaced.
   * The only field this ever reads back is the one it typed into.
   */
  function type(text, opts) {
    opts = opts || {};
    var el =
      opts.into && typeof opts.into === "string"
        ? document.querySelector(opts.into)
        : opts.into || document.activeElement;
    if (!el) return Promise.resolve({ ok: false, error: "no field" });
    text = String(text == null ? "" : text);
    var delays = Array.isArray(opts.delays) ? opts.delays : [];
    var typos = Array.isArray(opts.typos) ? opts.typos : [];
    var at = function (i) {
      if (!delays.length) return 55; // brain sent nothing: one flat fallback
      return delays[Math.min(i, delays.length - 1)];
    };
    var editable = el.isContentEditable && !("value" in el);

    // strokes win when they are there; otherwise the text + delays form
    var strokes = Array.isArray(opts.strokes) ? opts.strokes.slice() : null;
    if (!strokes) {
      strokes = [];
      for (var si = 0; si < text.length; si++) {
        for (var ti = 0; ti < typos.length; ti++)
          if (typos[ti].at === si) {
            strokes.push({ key: typos[ti].ch, delayMs: at(si) });
            strokes.push({ key: "\b", delayMs: typos[ti].pause || at(si) * 3 });
          }
        strokes.push({ key: text.charAt(si), delayMs: at(si) });
      }
    }

    var write = function (v) {
      if (editable) el.textContent = v;
      else setValue(el, v); // the native setter, so React notices
      el.dispatchEvent(new root.Event("input", { bubbles: true, composed: true }));
    };

    var c = centerOf(el);
    return O.cursor
      .moveTo(c.x, c.y, { ms: 460 })
      .then(function () {
        return O.cursor.press();
      })
      .then(function () {
        try {
          el.focus();
        } catch (e) {
          /* ignore */
        }
        var cur = "";
        var i = 0;
        return new Promise(function (done) {
          (function next() {
            if (stopped || i >= strokes.length) {
              el.dispatchEvent(new root.Event("change", { bubbles: true }));
              // the one field the agent ever reads: the box it just typed into
              return done({ ok: true, typed: editable ? el.textContent : el.value });
            }
            var st = strokes[i++] || {};
            var wait = st.delayMs == null ? 55 : st.delayMs;
            root.setTimeout(function () {
              if (st.key === "\b" || st.key === "Backspace") cur = cur.slice(0, -1);
              else cur += st.key == null ? "" : String(st.key);
              write(cur);
              next();
            }, wait);
          })();
        });
      });
  }

  function dwell(ms) {
    return O.cursor.breathe(Math.max(0, ms | 0)).then(function () {
      return { waited: ms | 0 };
    });
  }

  O.hands = {
    scroll: scroll,
    tapAt: tapAt,
    tapEl: tapEl,
    type: type,
    dwell: dwell,
    centerOf: centerOf,
    stop: function () {
      stopped = true;
    },
    resume: function () {
      stopped = false;
    },
    stopped: function () {
      return stopped;
    },
  };
})(window);

/* ---- agent/panel.js ---- */
/**
 * panel.js — the sheet inside the glass.
 *
 * Slides up from the home bar when you tap it (or the small grabber above it).
 * Shows the three platforms with a dot and a handle each, what the crew is
 * doing right now, the last few ticker lines, and Stop / Resume.
 *
 * It never acts on its own. Every press sends {t:"asked", ...} to the brain and
 * waits; the brain sends state back. The drag handle and the quit button send
 * {t:"window", ...}, which Swift handles because only Swift can.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.panel) return;

  var ID = "__organic_panel";
  var Z = 2147483645;
  var node = null;
  var sheet = null;
  var open = false;
  var lastAttach = 0;
  var observer = null;

  /**
   * Exactly the state the brain pushes. Nothing here is computed locally and
   * nothing is stored — a reload starts from this shape again.
   */
  var state = {
    phase: null,
    build: null,
    paused: false,
    stopped: false,
    doing: null,
    showing: null,
    mcp: null,
    accounts: [
      { platform: "instagram", state: "off", handle: null },
      { platform: "tiktok", state: "off", handle: null },
      { platform: "youtube", state: "off", handle: null },
    ],
    jobs: [],
    lines: [],
  };

  var LABEL = { instagram: "Instagram", tiktok: "TikTok", youtube: "YouTube" };

  var FONT =
    "-apple-system,BlinkMacSystemFont,'SF Pro Text','SF Pro Display',system-ui,sans-serif";

  function css() {
    return (
      "#" + ID + "{position:fixed;inset:0;z-index:" + Z + ";pointer-events:none;font-family:" +
      FONT + ";}" +
      "#" + ID + " .scrim{position:absolute;inset:0;background:rgba(0,0,0,0);" +
      "transition:background 220ms ease;pointer-events:none;}" +
      "#" + ID + ".on .scrim{background:rgba(0,0,0,.34);pointer-events:auto;}" +
      "#" + ID + " .grab{position:absolute;bottom:0;left:50%;transform:translateX(-50%);" +
      "width:170px;height:26px;pointer-events:auto;}" +
      "#" + ID + " .sheet{position:absolute;left:8px;right:8px;bottom:8px;" +
      "border-radius:26px;background:rgba(28,28,30,.82);" +
      "-webkit-backdrop-filter:blur(26px) saturate(180%);" +
      "backdrop-filter:blur(26px) saturate(180%);color:#fff;" +
      "box-shadow:0 -8px 40px rgba(0,0,0,.5),inset 0 0 0 .5px rgba(255,255,255,.14);" +
      "transform:translateY(112%);transition:transform 300ms cubic-bezier(.22,1,.36,1);" +
      "pointer-events:auto;padding:8px 0 14px;}" +
      "#" + ID + ".on .sheet{transform:translateY(0);}" +
      "#" + ID + " .bar{width:36px;height:5px;border-radius:3px;margin:0 auto 10px;" +
      "background:rgba(255,255,255,.3);}" +
      "#" + ID + " .row{display:flex;align-items:center;gap:10px;padding:9px 16px;" +
      "font-size:15px;line-height:20px;}" +
      "#" + ID + " .row+.row{box-shadow:inset 0 .5px 0 rgba(255,255,255,.1);}" +
      "#" + ID + " .row .grow{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;" +
      "white-space:nowrap;}" +
      "#" + ID + " .dot{width:9px;height:9px;border-radius:50%;background:rgba(255,255,255,.22);}" +
      "#" + ID + " .dot.on{background:#39FF7A;box-shadow:0 0 8px rgba(57,255,122,.8);}" +
      "#" + ID + " .sub{font-size:13px;color:rgba(235,235,245,.6);}" +
      "#" + ID + " .hd{font-size:12px;letter-spacing:.06em;text-transform:uppercase;" +
      "color:rgba(235,235,245,.5);padding:12px 16px 4px;}" +
      "#" + ID + " .tick{font-size:12px;color:rgba(235,235,245,.66);padding:2px 16px;" +
      "overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}" +
      "#" + ID + " .btns{display:flex;gap:8px;padding:12px 16px 2px;}" +
      "#" + ID + " .btn{flex:1;text-align:center;padding:11px 0;border-radius:14px;" +
      "font-size:15px;font-weight:600;background:rgba(120,120,128,.32);color:#fff;}" +
      "#" + ID + " .btn.stop{background:rgba(255,69,58,.9);}" +
      "#" + ID + " .btn.go{background:rgba(57,255,122,.9);color:#08210f;}" +
      "#" + ID + " .drag{padding:0 16px 2px;display:flex;align-items:center;gap:10px;" +
      "font-size:12px;color:rgba(235,235,245,.5);}" +
      "#" + ID + " .drag .move{flex:1;height:18px;}" +
      "#" + ID + " .quit{color:rgba(255,105,97,.95);font-weight:600;}"
    );
  }

  function send(msg) {
    if (O.send) O.send(msg);
  }

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }

  function render() {
    if (!sheet) return;
    var h = ['<div class="bar"></div>'];

    h.push('<div class="hd">Accounts</div>');
    (state.accounts || []).forEach(function (a) {
      var on = a.state === "on" || a.state === "connected" || a.state === true;
      var act = on ? "switch" : "connect";
      var sub = a.handle ? (a.handle.charAt(0) === "@" ? a.handle : "@" + a.handle) : on ? String(a.state) : "connect";
      h.push(
        '<div class="row" data-organic-do="' + act +
          '" data-organic-platform="' + esc(a.platform) +
          '"><span class="dot' + (on ? " on" : "") + '"></span>' +
          '<span class="grow">' + esc(a.label || LABEL[a.platform] || a.platform) + "</span>" +
          '<span class="sub">' + esc(sub) + "</span></div>",
      );
    });

    h.push('<div class="hd">Now</div>');
    var now = state.stopped
      ? "stopped"
      : state.paused
        ? "paused"
        : state.doing || state.showing || state.phase || "idle";
    h.push('<div class="row"><span class="grow">' + esc(now) + "</span>" +
      (state.build ? '<span class="sub">' + esc(state.build) + "</span>" : "") + "</div>");
    if (state.mcp) h.push('<div class="tick">mcp: ' + esc(state.mcp) + "</div>");

    var jobs = (state.jobs || []).slice(-3);
    if (jobs.length) {
      h.push('<div class="hd">Jobs</div>');
      jobs.forEach(function (j) {
        h.push('<div class="tick">' + esc((j.who ? j.who + " — " : "") + (j.what || "")) +
          (j.state ? " (" + esc(j.state) + ")" : "") + "</div>");
      });
    }

    var lines = (state.lines || []).slice(-5);
    if (lines.length) {
      h.push('<div class="hd">Lately</div>');
      lines.forEach(function (l) {
        var t = typeof l === "string" ? l : (l.who ? l.who + ": " : "") + (l.what || "");
        h.push('<div class="tick">' + esc(t) + "</div>");
      });
    }

    h.push(
      '<div class="btns"><div class="btn stop" data-organic-do="stop">Stop</div>' +
        '<div class="btn go" data-organic-do="resume">Resume</div></div>',
    );
    h.push(
      '<div class="drag"><span class="move" data-organic-window="move">drag to move</span>' +
        '<span class="quit" data-organic-do="quit" data-organic-window="quit">Quit</span></div>',
    );
    sheet.innerHTML = h.join("");
  }

  function build() {
    var el = document.createElement("div");
    el.id = ID;
    var style = document.createElement("style");
    style.textContent = css();
    el.appendChild(style);
    var scrim = document.createElement("div");
    scrim.className = "scrim";
    var grab = document.createElement("div");
    grab.className = "grab";
    sheet = document.createElement("div");
    sheet.className = "sheet";
    el.appendChild(scrim);
    el.appendChild(grab);
    el.appendChild(sheet);

    scrim.addEventListener("click", function () {
      setOpen(false);
    });
    grab.addEventListener("click", function () {
      setOpen(true);
    });

    sheet.addEventListener("click", function (ev) {
      var hit = null;
      var n = ev.target;
      while (n && n !== sheet) {
        if (n.getAttribute && (n.getAttribute("data-organic-do") || n.getAttribute("data-organic-window"))) {
          hit = n;
          break;
        }
        n = n.parentNode;
      }
      if (!hit) return;
      var act = hit.getAttribute("data-organic-do");
      var platform = hit.getAttribute("data-organic-platform") || null;
      if (act) {
        // The panel only ever asks. The brain decides and pushes state back.
        send({ t: "asked", do: act, platform: platform });
        if (act === "quit") send({ t: "window", do: "quit" });
        if (act === "stop" || act === "resume") setOpen(false);
        return;
      }
      var win = hit.getAttribute("data-organic-window");
      if (win) send({ t: "window", do: win });
    });

    // dragging the move strip asks Swift to move the window
    var last = null;
    var strip = function () {
      return sheet.querySelector('[data-organic-window="move"]');
    };
    sheet.addEventListener("pointerdown", function (ev) {
      if (ev.target === strip()) last = { x: ev.screenX, y: ev.screenY };
    });
    root.addEventListener("pointermove", function (ev) {
      if (!last) return;
      var dx = ev.screenX - last.x;
      var dy = ev.screenY - last.y;
      if (!dx && !dy) return;
      last = { x: ev.screenX, y: ev.screenY };
      send({ t: "window", do: "move", dx: dx, dy: dy });
    });
    root.addEventListener("pointerup", function () {
      last = null;
    });

    render();
    return el;
  }

  function attach() {
    var host = document.body || document.documentElement;
    if (!host) return;
    if (node && node.isConnected) return;
    node = build();
    host.appendChild(node);
    if (open) node.classList.add("on");
    lastAttach = Date.now();
  }

  function watch() {
    if (observer || !root.MutationObserver) return;
    observer = new root.MutationObserver(function () {
      if (node && node.isConnected) return;
      if (Date.now() - lastAttach < 1000) return;
      attach();
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
  }

  function setOpen(v) {
    attach();
    open = !!v;
    if (node) node.classList.toggle("on", open);
    return open;
  }

  O.panel = {
    mount: function () {
      if (document.body) {
        attach();
        watch();
      } else {
        document.addEventListener("DOMContentLoaded", function () {
          attach();
          watch();
        });
      }
      return true;
    },
    open: function () {
      return setOpen(true);
    },
    close: function () {
      return setOpen(false);
    },
    toggle: function () {
      return setOpen(!open);
    },
    isOpen: function () {
      return open;
    },
    /** The brain owns the contents. This only draws what it is given. */
    set: function (patch) {
      if (!patch) return state;
      [
        "phase", "build", "paused", "stopped", "doing", "showing", "mcp",
        "accounts", "jobs", "lines",
      ].forEach(function (k) {
        if (patch[k] !== undefined) state[k] = patch[k];
      });
      if (state.lines && state.lines.length > 20) state.lines = state.lines.slice(-20);
      render();
      return state;
    },
    tick: function (who, what) {
      state.lines = (state.lines || []).concat([{ who: who, what: what }]).slice(-20);
      render();
    },
    state: function () {
      return state;
    },
    el: function () {
      return node;
    },
  };
})(window);

/* ---- agent/index.js ---- */
/**
 * index.js — the entry. Builds window.__organic, wires the bridge, boots the
 * pieces.
 *
 * This bundle is injected at document start into EVERY frame and on EVERY
 * navigation, so it must be idempotent twice over: it runs only in the top
 * frame, and a second run on the same window is a no-op.
 *
 * It stores nothing, logs nothing that came out of a field, and never reads an
 * input's value except the comment box hands.type() just wrote to.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});

  // Only the top frame. An iframe gets the script too and must stay silent.
  try {
    if (root.top !== root.self) return;
  } catch (e) {
    return; // cross-origin parent: not the top frame we own
  }
  if (root.__organic && root.__organic.__booted) return;

  /** Post to Swift. In a plain browser (and in the tests) there is no handler. */
  function send(msg) {
    var text;
    try {
      text = JSON.stringify(msg);
    } catch (e) {
      return false;
    }
    try {
      if (
        root.webkit &&
        root.webkit.messageHandlers &&
        root.webkit.messageHandlers.organic &&
        typeof root.webkit.messageHandlers.organic.postMessage === "function"
      ) {
        root.webkit.messageHandlers.organic.postMessage(text);
        return true;
      }
    } catch (e) {
      /* the handler can vanish mid-navigation; never let that throw */
    }
    (root.__organic.sent = root.__organic.sent || []).push(msg);
    if (root.__organic.sent.length > 200) root.__organic.sent.shift();
    return false;
  }
  O.send = send;

  function tick(who, what) {
    O.panel.tick(who, what);
    send({ t: "tick", who: who, what: what });
  }

  /** The named things the brain taps: like, comment, next, profile. */
  function targetEl(name, a) {
    if (a && a.selector) return document.querySelector(a.selector);
    var s = O.sites[O.read.platform()];
    if (!s) return null;
    if (name === "like") return s.likeButton();
    if (name === "comment") return s.commentBox();
    if (name === "profile") return s.profileLink ? s.profileLink() : null;
    if (name === "reel") return s.openReel();
    return null;
  }

  var ACTS = {
    goto: function (a) {
      if (!a.url) throw new Error("goto needs a url");
      location.assign(a.url);
      return { going: a.url };
    },
    scroll: function (a) {
      return O.hands.scroll(a.px == null ? root.innerHeight : a.px, { pace: a.pace });
    },
    tap: function (a) {
      if (a.x != null && a.y != null)
        return O.hands.tapAt(a.x, a.y, a).then(function (r) {
          return { found: !!r.hit, changed: !!r.changed };
        });
      var name = a.target || a.what || null;
      var site = O.sites[O.read.platform()];
      // "next" is not a button on mobile: a reel advances by one viewport.
      if (name === "next") {
        var how = site && site.nextReel ? site.nextReel() : null;
        if (!how) return { found: false, changed: false };
        var y0 = root.scrollY;
        return O.hands.scroll(how.px, { pace: "skim" }).then(function () {
          return { found: true, changed: root.scrollY !== y0 };
        });
      }
      var el = targetEl(name, a);
      if (!el) return { found: false, changed: false }; // never a guess
      return O.hands.tapEl(el, a).then(function (r) {
        return { found: true, changed: !!r.changed, stillThere: !!r.stillThere };
      });
    },

    type: function (a) {
      var into = a.selector || null;
      var name = a.into || a.what || "comment";
      if (!into) into = targetEl(name === "comment" ? "comment" : name, {});
      if (!into) return { ok: false, error: "no field: " + name };
      // The brain sends the rhythm as strokes; the hands only play it.
      return O.hands.type(a.text, {
        into: into,
        strokes: a.strokes,
        delays: a.delays,
        typos: a.typos,
      });
    },

    dwell: function (a) {
      return O.hands.dwell(a.ms == null ? 800 : a.ms);
    },
    read: function (a) {
      var what = a.what || "page";
      if (what === "posts") return O.read.posts();
      if (what === "tags") return O.read.tags();
      if (what === "text") return O.read.bodyText(4000);
      if (what === "ads") return O.read.ads();
      if (what === "store") return O.read.store(a.url, a);
      if (what === "handle") return O.read.handle(a.platform);
      if (what === "signedIn") return O.read.signedIn(a.platform);
      return O.read.handle(a.platform).then(function (h) {
        return {
          url: location.href,
          platform: O.read.platform(),
          signedIn: O.read.signedIn(),
          handle: h,
          posts: O.read.posts(),
          tags: O.read.tags(),
        };
      });
    },

    say: function (a) {
      tick(a.who || "crew", a.what || "");
      return { said: true };
    },
    cursor: function (a) {
      if (a.label || a.name) O.cursor.setName(a.label || a.name);
      if (a.press) return O.cursor.press();
      if (a.x != null && a.y != null) return O.cursor.moveTo(a.x, a.y, { ms: a.ms });
      return O.cursor.at();
    },
    panel: function (a) {
      // `show` is tri-state: true opens, false closes, undefined just redraws.
      O.panel.set(a);
      if (a.show === true) O.panel.open();
      else if (a.show === false) O.panel.close();
      return { open: O.panel.isOpen() };
    },

    stop: function (a) {
      if (a.resume) {
        O.hands.resume();
        O.panel.set({ stopped: false, paused: false });
        return { stopped: false };
      }
      O.hands.stop();
      O.panel.set({ stopped: true });
      return { stopped: true };
    },
  };

  function fromApp(jsonText) {
    var msg;
    try {
      msg = typeof jsonText === "string" ? JSON.parse(jsonText) : jsonText;
    } catch (e) {
      return false;
    }
    if (!msg || msg.t !== "do") return false;
    var id = msg.id;
    var fn = ACTS[msg.act];
    if (!fn) {
      send({ t: "done", id: id, ok: false, result: null, error: "unknown act: " + msg.act });
      return false;
    }
    // `stop` must land even while something is in flight, so nothing is queued.
    Promise.resolve()
      .then(function () {
        return fn(msg);
      })
      .then(function (result) {
        send({ t: "done", id: id, ok: true, result: result == null ? null : result, error: null });
      })
      .catch(function (err) {
        send({
          t: "done",
          id: id,
          ok: false,
          result: null,
          error: (err && err.message) || String(err),
        });
      });
    return true;
  }

  function hello() {
    var base = {
      t: "hello",
      url: location.href,
      platform: O.read.platform(),
      signedIn: O.read.signedIn(),
    };
    return O.read
      .handle()
      .then(function (h) {
        base.handle = h;
        send(base);
        return base;
      })
      .catch(function () {
        base.handle = null;
        send(base);
        return base;
      });
  }

  root.__organic = {
    __booted: true,
    version: 1,
    fromApp: fromApp,
    send: send,
    ns: O,
    // handy for the app and the tests; none of these keep state anywhere
    cursor: O.cursor,
    hands: O.hands,
    read: O.read,
    panel: O.panel,
    sites: O.sites,
    find: O.find,
    bezel: O.bezel,
    hello: hello,
  };

  function boot() {
    O.bezel.mount();
    O.cursor.mount();
    O.panel.mount();
    hello();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot, { once: true });
  } else {
    boot();
  }
})(window);

