/**
 * build.mjs — concatenate the agent into one file the worker serves as
 * agent.js. No bundler, no imports at runtime: every piece is an IIFE that
 * hangs itself off window.__organicNS, so plain concatenation in dependency
 * order is the whole build.
 *
 *   node tools/organic/worker/agent/build.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "agent.built.js");

// dependency order: finders, then the pieces that use them, entry last
export const ORDER = [
  "bezel.js",
  "cursor.js",
  "sites/common.js",
  "sites/instagram.js",
  "sites/tiktok.js",
  "sites/youtube.js",
  // the supplier desk: his own Alibaba and 1688, signed in by him
  "sites/alibaba.js",
  "read.js",
  "hands.js",
  "panel.js",
  "index.js",
];

export function build() {
  const parts = ORDER.map((f) => {
    const src = readFileSync(join(here, f), "utf8");
    return "/* ---- agent/" + f + " ---- */\n" + src.trim() + "\n";
  });
  return (
    "/* The agent bundle — generated by agent/build.mjs. Do not edit. */\n" +
    parts.join("\n") +
    "\n"
  );
}

const text = build();
writeFileSync(out, text);
console.log("agent.built.js  " + text.split("\n").length + " lines  " + text.length + " bytes");
