/* The agent bundle — generated by agent/build.mjs. Do not edit. */
/* ---- agent/bezel.js ---- */
/**
 * bezel.js — the phone drawn over the page.
 *
 * A fixed rounded frame with an inner shadow ring and a 1px light rim, the
 * Dynamic Island as a black pill at the top, and the home indicator bar at the
 * bottom. Everything here is pointer-events:none and lives at the top of the
 * stack, so it cannot block a scroll or a click anywhere on the real page.
 *
 * Sites rewrite their own DOM constantly. A MutationObserver re-attaches the
 * bezel if it is removed, throttled to at most once a second so a busy feed
 * cannot turn this into a re-render loop.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.bezel) return;

  var ID = "__organic_bezel";
  var Z = 2147483640; // just under the cursor, which must sit over everything
  var node = null;
  var lastAttach = 0;
  var observer = null;

  function css() {
    return (
      "#" + ID + "{position:fixed;inset:0;z-index:" + Z + ";pointer-events:none;" +
      "contain:strict;}" +
      "#" + ID + " .frame{position:absolute;inset:0;border-radius:46px;" +
      "box-shadow:inset 0 0 0 1px rgba(255,255,255,.28)," +
      "inset 0 0 0 3px rgba(0,0,0,.92)," +
      "inset 0 0 22px 6px rgba(0,0,0,.45);}" +
      "#" + ID + " .island{position:absolute;top:10px;left:50%;" +
      "transform:translateX(-50%);width:104px;height:31px;border-radius:18px;" +
      "background:#000;box-shadow:0 0 0 1px rgba(255,255,255,.06);}" +
      "#" + ID + " .home{position:absolute;bottom:7px;left:50%;" +
      "transform:translateX(-50%);width:134px;height:5px;border-radius:3px;" +
      "background:rgba(0,0,0,.72);box-shadow:0 0 0 1px rgba(255,255,255,.18);}"
    );
  }

  function build() {
    var el = document.createElement("div");
    el.id = ID;
    el.setAttribute("aria-hidden", "true");
    var style = document.createElement("style");
    style.textContent = css();
    el.appendChild(style);
    ["frame", "island", "home"].forEach(function (name) {
      var part = document.createElement("div");
      part.className = name;
      el.appendChild(part);
    });
    return el;
  }

  function attach() {
    var host = document.body || document.documentElement;
    if (!host) return;
    if (node && node.isConnected) return;
    node = build();
    host.appendChild(node);
    lastAttach = Date.now();
  }

  function watch() {
    if (observer || !root.MutationObserver) return;
    observer = new root.MutationObserver(function () {
      if (node && node.isConnected) return;
      if (Date.now() - lastAttach < 1000) return; // at most once a second
      attach();
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
  }

  O.bezel = {
    mount: function () {
      if (document.body) {
        attach();
        watch();
      } else {
        document.addEventListener("DOMContentLoaded", function () {
          attach();
          watch();
        });
      }
      return true;
    },
    /** The home bar's hit box, so the panel's grabber can sit exactly on it. */
    homeRect: function () {
      var bar = node && node.querySelector(".home");
      return bar ? bar.getBoundingClientRect() : null;
    },
    el: function () {
      return node;
    },
  };
})(window);

/* ---- agent/cursor.js ---- */
/**
 * cursor.js — the green thing Alex watches.
 *
 * A #39FF7A dot with a soft halo, a ring that pulses outward, and a small name
 * label. moveTo() glides along a slightly curved path with eased, wobbly steps
 * at 60fps: never a jump, never a straight line. press() squashes the dot and
 * throws a ripple where it stands.
 *
 * Pointer-events none and the highest z-index there is, so it is visible over
 * the page and never in the way of it. Like the bezel it re-attaches itself if
 * the page throws it away.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.cursor) return;

  var ID = "__organic_cursor";
  var Z = 2147483647;
  var node = null;
  var dot = null;
  var label = null;
  var lastAttach = 0;
  var observer = null;
  var x = 0;
  var y = 0;
  var moving = null; // a token so a new move cancels the one in flight

  function css() {
    return (
      "#" + ID + "{position:fixed;left:0;top:0;z-index:" + Z + ";" +
      "pointer-events:none;will-change:transform;}" +
      "#" + ID + " .dot{position:absolute;left:-9px;top:-9px;width:18px;" +
      "height:18px;border-radius:50%;background:#39FF7A;" +
      "box-shadow:0 0 10px 3px rgba(57,255,122,.75),0 0 28px 12px rgba(57,255,122,.28);" +
      "transition:transform 90ms ease-out;}" +
      "#" + ID + " .ring{position:absolute;left:-9px;top:-9px;width:18px;" +
      "height:18px;border-radius:50%;border:2px solid rgba(57,255,122,.7);" +
      "animation:__organic_pulse 1.6s ease-out infinite;}" +
      "#" + ID + " .name{position:absolute;left:16px;top:8px;font:600 11px/1.4 " +
      "-apple-system,BlinkMacSystemFont,'SF Pro Text',system-ui,sans-serif;" +
      "color:#0b1b10;background:#39FF7A;padding:1px 6px;border-radius:7px;" +
      "white-space:nowrap;box-shadow:0 1px 6px rgba(0,0,0,.35);}" +
      "#" + ID + " .ripple{position:absolute;left:-9px;top:-9px;width:18px;" +
      "height:18px;border-radius:50%;border:2px solid rgba(57,255,122,.9);" +
      "animation:__organic_ripple 420ms ease-out forwards;}" +
      "@keyframes __organic_pulse{0%{transform:scale(1);opacity:.85}" +
      "100%{transform:scale(2.6);opacity:0}}" +
      "@keyframes __organic_ripple{0%{transform:scale(1);opacity:.9}" +
      "100%{transform:scale(3.4);opacity:0}}"
    );
  }

  function build() {
    var el = document.createElement("div");
    el.id = ID;
    el.setAttribute("aria-hidden", "true");
    var style = document.createElement("style");
    style.textContent = css();
    el.appendChild(style);
    var ring = document.createElement("div");
    ring.className = "ring";
    dot = document.createElement("div");
    dot.className = "dot";
    label = document.createElement("div");
    label.className = "name";
    label.textContent = O.cursorName || "Bea";
    el.appendChild(ring);
    el.appendChild(dot);
    el.appendChild(label);
    return el;
  }

  function attach() {
    var host = document.body || document.documentElement;
    if (!host) return;
    if (node && node.isConnected) return;
    node = build();
    host.appendChild(node);
    place();
    lastAttach = Date.now();
  }

  function watch() {
    if (observer || !root.MutationObserver) return;
    observer = new root.MutationObserver(function () {
      if (node && node.isConnected) return;
      if (Date.now() - lastAttach < 1000) return;
      attach();
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
  }

  function place() {
    if (node) node.style.transform = "translate3d(" + x.toFixed(2) + "px," + y.toFixed(2) + "px,0)";
  }

  var easeInOut = function (t) {
    return t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
  };

  function moveTo(tx, ty, opts) {
    opts = opts || {};
    attach();
    var ms = Math.max(120, opts.ms || 520);
    var sx = x;
    var sy = y;
    var dx = tx - sx;
    var dy = ty - sy;
    var dist = Math.sqrt(dx * dx + dy * dy);
    // One control point off to the side gives the arc; the side flips at random
    // so two moves in a row never trace the same line.
    var bow = (dist * 0.18 + 8) * (Math.random() < 0.5 ? -1 : 1);
    var cx = sx + dx / 2 - (dy / (dist || 1)) * bow;
    var cy = sy + dy / 2 + (dx / (dist || 1)) * bow;
    var token = {};
    moving = token;
    var t0 = 0;
    return new Promise(function (done) {
      function frame(now) {
        if (moving !== token) return done(false);
        if (!t0) t0 = now;
        var p = Math.min(1, (now - t0) / ms);
        var e = easeInOut(p);
        var inv = 1 - e;
        // quadratic bezier through the control point
        var px = inv * inv * sx + 2 * inv * e * cx + e * e * tx;
        var py = inv * inv * sy + 2 * inv * e * cy + e * e * ty;
        // a little hand-shake, fading out as it lands
        var wob = (1 - e) * 1.6;
        x = px + (Math.random() - 0.5) * wob;
        y = py + (Math.random() - 0.5) * wob;
        place();
        if (p < 1) return root.requestAnimationFrame(frame);
        x = tx;
        y = ty;
        place();
        moving = null;
        done(true);
      }
      root.requestAnimationFrame(frame);
    });
  }

  function press() {
    attach();
    if (dot) {
      dot.style.transform = "scale(.62)";
      root.setTimeout(function () {
        if (dot) dot.style.transform = "scale(1)";
      }, 110);
    }
    if (node) {
      var r = document.createElement("div");
      r.className = "ripple";
      node.appendChild(r);
      root.setTimeout(function () {
        if (r.parentNode) r.parentNode.removeChild(r);
      }, 450);
    }
    return Promise.resolve(true);
  }

  /** dwell keeps it alive: a tiny drift so it never looks frozen. */
  function breathe(ms) {
    var t0 = Date.now();
    return new Promise(function (done) {
      (function step() {
        if (Date.now() - t0 >= ms) return done(true);
        x += (Math.random() - 0.5) * 0.7;
        y += (Math.random() - 0.5) * 0.7;
        place();
        root.setTimeout(step, 90);
      })();
    });
  }

  O.cursor = {
    mount: function () {
      if (document.body) {
        attach();
        watch();
      } else {
        document.addEventListener("DOMContentLoaded", function () {
          attach();
          watch();
        });
      }
      if (!x && !y) {
        x = Math.round((root.innerWidth || 390) / 2);
        y = Math.round((root.innerHeight || 844) * 0.62);
        place();
      }
      return true;
    },
    moveTo: moveTo,
    press: press,
    breathe: breathe,
    at: function () {
      return { x: x, y: y };
    },
    setName: function (n) {
      O.cursorName = String(n || "Bea");
      if (label) label.textContent = O.cursorName;
    },
    el: function () {
      return node;
    },
  };
})(window);

/* ---- agent/sites/common.js ---- */
/**
 * sites/common.js — the finders every recipe is built out of.
 *
 * Role, aria-label, visible text. Never a generated class name. Every finder
 * returns null when it finds nothing, so a recipe can say "I could not find
 * the like button" instead of pressing whatever happened to be nearby.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.find) return;
  O.sites = O.sites || {};

  function visible(el) {
    if (!el || !el.getBoundingClientRect) return false;
    var r = el.getBoundingClientRect();
    if (r.width < 2 || r.height < 2) return false;
    var st = root.getComputedStyle ? root.getComputedStyle(el) : null;
    if (st && (st.visibility === "hidden" || st.display === "none" || st.opacity === "0"))
      return false;
    return true;
  }

  function all(sel, scope) {
    return Array.prototype.slice.call((scope || document).querySelectorAll(sel));
  }

  /** Elements whose aria-label matches, exactly or by a regexp. */
  function byLabel(match, scope) {
    var test =
      match instanceof RegExp
        ? function (v) {
            return match.test(v);
          }
        : function (v) {
            return v.toLowerCase() === String(match).toLowerCase();
          };
    return all("[aria-label]", scope).filter(function (el) {
      return test((el.getAttribute("aria-label") || "").trim()) && visible(el);
    });
  }

  function oneByLabel(match, scope) {
    var hits = byLabel(match, scope);
    return hits.length ? hits[0] : null;
  }

  /** Elements with an explicit or implicit role. */
  function byRole(role, scope) {
    var implicit = { button: "button", link: "a[href]", textbox: "input,textarea" }[role] || "";
    var sel = '[role="' + role + '"]' + (implicit ? "," + implicit : "");
    return all(sel, scope).filter(visible);
  }

  /** The first element of a role whose visible text matches. */
  function byText(role, match, scope) {
    var test =
      match instanceof RegExp
        ? function (v) {
            return match.test(v);
          }
        : function (v) {
            return v.toLowerCase().indexOf(String(match).toLowerCase()) >= 0;
          };
    var hits = byRole(role, scope).filter(function (el) {
      return test(((el.innerText || el.textContent || "") + "").replace(/\s+/g, " ").trim());
    });
    return hits.length ? hits[0] : null;
  }

  /** A text field: role=textbox, contenteditable, or a labelled input. */
  function field(match, scope) {
    var labelled = byLabel(match, scope).filter(function (el) {
      return (
        el.tagName === "INPUT" ||
        el.tagName === "TEXTAREA" ||
        el.isContentEditable ||
        el.getAttribute("role") === "textbox"
      );
    });
    if (labelled.length) return labelled[0];
    var ph = all("input[placeholder],textarea[placeholder]", scope).filter(function (el) {
      var p = el.getAttribute("placeholder") || "";
      return (match instanceof RegExp ? match.test(p) : p.toLowerCase().indexOf(String(match).toLowerCase()) >= 0) && visible(el);
    });
    if (ph.length) return ph[0];
    var ce = all('[contenteditable="true"],[role="textbox"]', scope).filter(visible);
    return ce.length ? ce[0] : null;
  }

  /** The nearest ancestor that behaves like a button (for an icon inside one). */
  function clickable(el) {
    var n = el;
    for (var i = 0; n && i < 6; i++, n = n.parentElement) {
      if (!n.tagName) continue;
      if (n.tagName === "BUTTON" || n.getAttribute("role") === "button" || n.tagName === "A")
        return n;
    }
    return el;
  }

  O.find = {
    visible: visible,
    all: all,
    byLabel: byLabel,
    oneByLabel: oneByLabel,
    byRole: byRole,
    byText: byText,
    field: field,
    clickable: clickable,
  };
})(window);

/* ---- agent/sites/fiverr.js ---- */
/**
 * Fiverr, as the desk sees it.
 *
 * The other desks in this app are for spending money. This one is for earning
 * it, which changes almost nothing about how it is read and everything about
 * what it must never do.
 *
 * Fiverr bans fully automated order fulfilment, says so plainly, and looks for
 * it. So nothing here delivers an order, accepts one, or sends a message. It
 * reads: what is waiting, who is asking, what they asked for. The drafting
 * happens in the brain and the sending happens when Alex taps approve, on his
 * own machine, in his own session — which is him working quickly, not a bot
 * wearing his name. That distinction is the whole reason this file is a reader
 * and not a hand.
 *
 * Every selector here is a guess at somebody else's markup, so each reader
 * tries several and stops at the first that gives something defensible. When
 * none of them do the answer is null or [] — never a zero, never an invented
 * due date. A wrong deadline on this screen costs a late delivery and a rating.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  var S = O.sites || (O.sites = {});
  if (S.fiverr) return;

  function text(el) {
    return el ? String(el.innerText || el.textContent || "").trim() : "";
  }
  function flat(el) {
    return text(el).replace(/\s+/g, " ");
  }
  function abs(href) {
    if (!href) return null;
    try { return new URL(href, location.href).href; } catch (e) { return null; }
  }
  function one(sels, scope) {
    for (var i = 0; i < sels.length; i++) {
      var el;
      try { el = (scope || document).querySelector(sels[i]); } catch (e) { continue; }
      if (el) return el;
    }
    return null;
  }
  function all(sels, scope) {
    var out = [], seen = [];
    for (var i = 0; i < sels.length; i++) {
      var hits;
      try { hits = (scope || document).querySelectorAll(sels[i]); } catch (e) { continue; }
      for (var j = 0; j < hits.length; j++) {
        if (seen.indexOf(hits[j]) >= 0) continue;
        seen.push(hits[j]); out.push(hits[j]);
      }
    }
    return out;
  }

  /** "$45", "US$ 1,200.00" → 4500 / 120000. Null when there is no number. */
  function moneyCents(s) {
    var m = /(?:US)?\$\s*([\d,]+(?:\.\d{1,2})?)/.exec(String(s || ""));
    if (!m) return null;
    var n = Number(m[1].replace(/,/g, ""));
    return Number.isFinite(n) ? Math.round(n * 100) : null;
  }

  /**
   * "2 days left", "23 hours left", "Late" → minutes remaining, or null.
   *
   * Read rather than computed from a date, because Fiverr prints the countdown
   * and prints it in the buyer's terms. A negative number means late, and late
   * is said as late rather than rounded up to zero.
   */
  function minutesLeft(s) {
    var t = String(s || "").toLowerCase();
    if (/\blate\b|overdue/.test(t)) return -1;
    var d = /(\d+)\s*day/.exec(t);
    var h = /(\d+)\s*hour/.exec(t);
    var m = /(\d+)\s*min/.exec(t);
    if (!d && !h && !m) return null;
    return (d ? Number(d[1]) * 1440 : 0) + (h ? Number(h[1]) * 60 : 0) + (m ? Number(m[1]) : 0);
  }

  function isLoginPage() {
    if (/\/login|\/join|\/sign_?in/i.test(location.pathname)) return true;
    return !!one(['form[action*="login" i] input[type="password"]', 'input[name="password"]']);
  }

  S.fiverr = {
    match: function (host) {
      return /(^|\.)fiverr\.com$/.test(host);
    },

    site: function () { return "fiverr"; },

    isLoginPage: isLoginPage,

    /**
     * Signed in, in layers, because Fiverr serves a marketing header to a
     * stranger and an account header to a seller, and neither is labelled:
     *   1. a password box on screen — definitely not
     *   2. the seller's own menu (avatar, "Switch to Buying")
     *   3. a "Join"/"Sign in" pair with nothing beside them — definitely not
     * When none of it is on the page the answer is false, because "probably
     * signed in" is how an app posts as nobody.
     */
    signedIn: function () {
      if (isLoginPage()) return false;
      if (one(['[class*="avatar" i] img', '[data-testid*="user-menu" i]', 'a[href*="/users/"] img'])) return true;
      var switcher = all(['a, button']).filter(function (el) {
        return /switch to (buying|selling)/i.test(flat(el));
      });
      if (switcher.length) return true;
      return false;
    },

    /** The seller's own handle, when the page states it. Never invented. */
    who: function () {
      var a = one(['a[href^="/users/"]']);
      var m = a && /\/users\/([^/?#]+)/.exec(a.getAttribute("href") || "");
      return m ? "@" + m[1] : null;
    },

    statusUrl: "https://www.fiverr.com/seller_dashboard",

    /**
     * What is waiting for work, as rows.
     *
     * This is the list the desk actually plans from: an active order with a
     * countdown is the only thing on Fiverr that is already money. Briefs and
     * requests are possibilities; these are commitments.
     */
    results: function () {
      var rows = all([
        '[class*="order-row" i]',
        'table tbody tr',
        '[data-testid*="order" i]',
      ]);
      var out = [];
      for (var i = 0; i < rows.length; i++) {
        var row = rows[i];
        var line = flat(row);
        if (!line || line.length < 8) continue;
        var link = one(['a[href*="/orders/"]', 'a[href*="/inbox/"]'], row);
        var href = link ? abs(link.getAttribute("href")) : null;
        var due = minutesLeft(line);
        var cents = moneyCents(line);
        // A row that is neither money nor a deadline is chrome, not an order.
        if (due == null && cents == null) continue;
        out.push({
          url: href,
          title: link ? flat(link) : null,
          buyer: (function () {
            var b = one(['a[href^="/users/"]', '[class*="username" i]'], row);
            return b ? flat(b) : null;
          })(),
          dueInMinutes: due,
          late: due != null && due < 0,
          priceCents: cents,
          line: line.slice(0, 300),
        });
      }
      return out;
    },

    /** The inbox, as a list of conversations. */
    threads: function () {
      var rows = all([
        '[class*="conversation" i] li',
        '[data-testid*="conversation" i]',
        'ul[class*="inbox" i] li',
      ]);
      var out = [];
      for (var i = 0; i < rows.length; i++) {
        var row = rows[i];
        var line = flat(row);
        if (!line) continue;
        var who = one(['[class*="username" i]', 'a[href^="/users/"]', 'strong', 'b'], row);
        out.push({
          who: who ? flat(who) : null,
          preview: line.slice(0, 220),
          unread: /\bunread\b/i.test(row.className || "") || !!one(['[class*="unread" i]'], row),
          url: (function () {
            var a = one(['a[href*="/inbox/"]'], row);
            return a ? abs(a.getAttribute("href")) : null;
          })(),
        });
      }
      return out;
    },

    /**
     * The messages in whatever conversation is open.
     *
     * `mine` is left undefined rather than guessed when the page gives no
     * side: the brain writes a reply off this, and mistaking the buyer's words
     * for our own is how an app answers itself.
     */
    messages: function () {
      var rows = all([
        '[class*="message-row" i]',
        '[class*="bubble" i]',
        '[data-testid*="message" i]',
      ]);
      var out = [];
      for (var i = 0; i < rows.length; i++) {
        var row = rows[i];
        var body = one(['[class*="body" i]', '[class*="text" i]', 'p'], row) || row;
        var t = flat(body);
        if (!t) continue;
        var cls = String(row.className || "");
        var mine = /\b(mine|self|outgoing|sent)\b/i.test(cls)
          ? true
          : /\b(theirs|other|incoming|received)\b/i.test(cls)
            ? false
            : undefined;
        out.push({
          text: t.slice(0, 4000),
          mine: mine,
          at: (function () {
            var el = one(['time', '[class*="time" i]', '[class*="date" i]'], row);
            return el ? (el.getAttribute("datetime") || flat(el)) : null;
          })(),
        });
      }
      return out;
    },

    /** Open a named conversation. Reading only — it never types or sends. */
    openThread: function (who) {
      var want = String(who || "").replace(/^@/, "").toLowerCase();
      if (!want) return false;
      var links = all(['a[href*="/inbox/"]']);
      for (var i = 0; i < links.length; i++) {
        var href = links[i].getAttribute("href") || "";
        if (href.toLowerCase().indexOf(want) >= 0 || flat(links[i]).toLowerCase().indexOf(want) >= 0) {
          links[i].click();
          return true;
        }
      }
      return false;
    },

    /**
     * How the shop is doing, when the dashboard says so.
     *
     * Every field is null until the page prints it. A rating this app invented
     * would end up in a decision about whether to take more work.
     */
    readStatus: function () {
      var page = flat(document.body).slice(0, 12000);
      function after(label) {
        var re = new RegExp(label + "\\s*[:\\n]?\\s*([\\d.,]+%?)", "i");
        var m = re.exec(page);
        return m ? m[1] : null;
      }
      return {
        rating: after("rating"),
        responseRate: after("response rate"),
        onTime: after("delivered on time|on-time delivery"),
        completion: after("order completion"),
      };
    },
  };

  // Exposed for the tests, which feed them strings rather than a page.
  S.fiverr.parse = { moneyCents: moneyCents, minutesLeft: minutesLeft };
})(window);

/* ---- agent/read.js ---- */
/**
 * read.js — reading the page for the crew.
 *
 * Everything here is found by role, aria-label and visible text. Never by a
 * generated class name, because those change weekly. When something is not
 * found this returns null or an empty list — it never guesses.
 *
 * It reads no input values at all. The one field the agent ever reads back is
 * the comment box hands.type() just wrote to, and that read lives there.
 *
 * The brain asks for exactly these: signedIn, handle, text, posts, tags, ads,
 * store.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.read) return;

  function text(el) {
    if (!el) return "";
    return (el.innerText || el.textContent || "").replace(/\s+/g, " ").trim();
  }

  function platform() {
    var h = location.hostname || "";
    if (/instagram\./.test(h)) return "instagram";
    if (/tiktok\./.test(h)) return "tiktok";
    if (/youtube\./.test(h)) return "youtube";
    return "unknown";
  }

  /**
   * The desk's recipes say which host they are for, rather than being looked
   * up by a platform name — WhatsApp and Alibaba are not "platforms" in the
   * sense the rest of this file means.
   */
  function deskSite() {
    var host = location.hostname;
    var all = O.sites || {};
    for (var key in all) {
      if (all[key] && typeof all[key].match === "function" && all[key].match(host)) return all[key];
    }
    return null;
  }

  function site(which) {
    var p = which || platform();
    return (O.sites && O.sites[p]) || null;
  }

  /** Signed in when the platform recipe says so; unknown platform => false. */
  /**
   * The account's own id, from the cookie the site sets about itself.
   *
   * Proof that somebody is signed in, and a name to work under while the
   * real handle is still being asked for. A platform refusing to say WHO is
   * not a reason to stand still — it is a reason to keep asking.
   */
  function userId() {
    var m = /(^|;\s*)ds_user_id=(\d+)/.exec(document.cookie || "");
    return m ? m[2] : null;
  }

  function signedIn(which) {
    var s = site(which);
    if (!s) return false;
    if (s.isLoginPage()) return false;
    return !!s.signedIn();
  }

  /**
   * Our own handle as "@name", or null. A connection with no readable handle
   * is not a connection. Async, because Instagram's best answer is a fetch.
   */
  function handle(which) {
    var s = site(which);
    if (!s) return Promise.resolve(null);
    var got = s.handleAsync ? s.handleAsync() : Promise.resolve(s.handle());
    return Promise.resolve(got)
      .then(function (h) {
        if (!h) return null;
        h = String(h).trim().replace(/^@+/, "");
        // never an email address — that bug shipped once on YouTube
        if (!h || h.indexOf("@") >= 0 || /\.(com|net|org|co)$/i.test(h)) return null;
        if (!/^[A-Za-z0-9._-]{2,40}$/.test(h)) return null;
        return "@" + h;
      })
      .catch(function () {
        return null;
      });
  }

  /** The first ~4000 characters the page shows. The brain looks for friction. */
  function bodyText(max) {
    var b = document.body;
    if (!b) return "";
    var t = b.innerText || b.textContent || "";
    return t.slice(0, max || 4000);
  }

  var NUM = /([\d][\d.,]*)\s*([KMB])?\s*(likes?|views?|plays?|comments?)/i;

  function countsIn(el) {
    var out = {};
    var take = function (m) {
      if (!m) return;
      var n = parseFloat(m[1].replace(/,/g, ""));
      var mult = { K: 1e3, M: 1e6, B: 1e9 }[(m[2] || "").toUpperCase()] || 1;
      var kind = m[3].toLowerCase().replace(/s$/, "");
      if (kind === "play") kind = "view";
      if (out[kind] == null) out[kind] = Math.round(n * mult);
    };
    var re = new RegExp(NUM.source, "gi");
    var t = text(el);
    var m;
    while ((m = re.exec(t))) take(m);
    var labelled = el.querySelectorAll("[aria-label]");
    for (var i = 0; i < labelled.length; i++) take(NUM.exec(labelled[i].getAttribute("aria-label") || ""));
    return out;
  }

  function handleIn(el) {
    var links = el.querySelectorAll('a[href^="/@"], a[href*="/@"]');
    for (var i = 0; i < links.length; i++) {
      var m = /\/@([A-Za-z0-9._]+)/.exec(links[i].getAttribute("href") || "");
      if (m) return "@" + m[1];
    }
    var m2 = /@([A-Za-z0-9._]{2,30})/.exec(text(el));
    if (m2) return "@" + m2[1];
    var byRole = el.querySelector("a[href]");
    if (byRole) {
      var m3 = /^\/([A-Za-z0-9._]{2,30})\/?$/.exec(byRole.getAttribute("href") || "");
      if (m3) return "@" + m3[1];
    }
    return null;
  }

  function abs(href) {
    try {
      return new URL(href, location.href).href;
    } catch (e) {
      return href || null;
    }
  }

  function urlIn(el) {
    var a =
      el.querySelector('a[href*="/reel/"], a[href*="/p/"], a[href*="/video/"], a[href*="/shorts/"]') ||
      el.querySelector("a[href]");
    return a ? abs(a.getAttribute("href")) : null;
  }

  /** Posts on screen: {url, handle, views, ...}. Deduped by url, at most 40. */
  function posts() {
    var s = site();
    var nodes = (s && s.postNodes && s.postNodes()) || [];
    if (!nodes.length) nodes = Array.prototype.slice.call(document.querySelectorAll("article"));
    if (!nodes.length)
      nodes = Array.prototype.slice.call(document.querySelectorAll('[role="article"]'));
    var seen = Object.create(null);
    var out = [];
    for (var i = 0; i < nodes.length && out.length < 40; i++) {
      var el = nodes[i];
      var c = countsIn(el);
      var url = urlIn(el);
      var h = handleIn(el);
      var key = url || (h || "") + "#" + i;
      if (seen[key]) continue;
      seen[key] = 1;
      out.push({
        url: url,
        handle: h,
        views: c.view == null ? null : c.view,
        likes: c.like == null ? null : c.like,
        comments: c.comment == null ? null : c.comment,
        caption: captionOf(el),
      });
    }
    return out;
  }

  /**
   * The hashtags this page carries: the ones the platform itself links
   * (/explore/tags/x/, /tag/x) plus #word in the captions. Most-seen first,
   * at most 20.
   */
  function tags(scope) {
    var root_ = scope || document.body || document.documentElement;
    if (!root_) return [];
    var count = Object.create(null);
    var order = [];
    var push = function (t) {
      var v = "#" + String(t).replace(/^#/, "").toLowerCase();
      if (!/^#[a-z0-9_]{2,60}$/.test(v)) return;
      if (count[v] == null) {
        count[v] = 0;
        order.push(v);
      }
      count[v]++;
    };
    var links = root_.querySelectorAll('a[href*="/explore/tags/"], a[href*="/tag/"]');
    for (var i = 0; i < links.length; i++) {
      var href = links[i].getAttribute("href") || "";
      var m = /\/(?:explore\/tags|tag)\/([^/?#]+)/.exec(href);
      if (m) push(decodeURIComponent(m[1]));
      else {
        var t = text(links[i]);
        if (/^#/.test(t)) push(t);
      }
    }
    var re = /#[A-Za-z0-9_]{2,60}/g;
    var body = text(root_);
    var mm;
    while ((mm = re.exec(body))) push(mm[0]);
    order.sort(function (a, b) {
      return count[b] - count[a];
    });
    return order.slice(0, 20);
  }

  /** The caption of a post element: the recipe knows, otherwise longest text. */
  function captionOf(el) {
    if (!el) return null;
    var s = site();
    if (s && s.captionOf) {
      var viaSite = s.captionOf(el);
      if (viaSite != null) return viaSite;
    }
    var best = null;
    var cands = el.querySelectorAll("p, h1, h2, span, div");
    for (var i = 0; i < cands.length; i++) {
      if (cands[i].children.length) continue; // leaves only
      var t = text(cands[i]);
      if (t.length < 8) continue;
      if (NUM.test(t)) continue;
      if (!best || t.length > best.length) best = t;
    }
    return best;
  }

  /**
   * The Meta Ad Library, read off the visible cards.
   * `started` is the date exactly as printed ("Started running on Aug 2, 2026"
   * gives "Aug 2, 2026"). A card with no advertiser is skipped rather than
   * guessed at.
   */
  function ads() {
    var cards = Array.prototype.slice.call(
      document.querySelectorAll('[role="article"], article, [data-testid*="ad" i]'),
    );
    if (!cards.length) {
      // the library also renders each result as a plain block with the
      // "Library ID" line in it; take those blocks' nearest sized ancestor
      var ids = Array.prototype.slice.call(document.querySelectorAll("div,section")).filter(function (n) {
        return !n.querySelector("div,section") && /Library ID/i.test(text(n));
      });
      cards = ids
        .map(function (n) {
          var p = n;
          for (var i = 0; i < 4 && p.parentElement; i++) p = p.parentElement;
          return p;
        })
        .filter(Boolean);
    }
    var seen = Object.create(null);
    var out = [];
    for (var i = 0; i < cards.length && out.length < 40; i++) {
      var el = cards[i];
      var t = text(el);
      if (!/Library ID|Started running|Sponsored/i.test(t)) continue;
      var startedM = /Started running on\s+([A-Za-z]{3,9}\s+\d{1,2},\s+\d{4})/.exec(t);
      var link = el.querySelector('a[href*="http"], a[href^="/"]');
      var name = null;
      var nameEl = el.querySelector("a[href] span, a[href] strong, a[href]");
      if (nameEl) name = text(nameEl);
      if (!name) {
        var m = /Sponsored\s*·?\s*([^\n·]{2,60})/.exec(t);
        if (m) name = m[1].trim();
      }
      if (!name) continue; // no advertiser: skip, do not guess
      var body = t
        .replace(/Started running on\s+[A-Za-z]{3,9}\s+\d{1,2},\s+\d{4}/i, " ")
        .replace(/Library ID:?\s*\d+/i, " ")
        .replace(/Sponsored/i, " ")
        .replace(name, " ")
        .replace(/\s+/g, " ")
        .trim();
      var url = link ? abs(link.getAttribute("href")) : null;
      var key = name + "|" + (startedM ? startedM[1] : "") + "|" + body.slice(0, 60);
      if (seen[key]) continue;
      seen[key] = 1;
      out.push({
        advertiser: name,
        started: startedM ? startedM[1] : null,
        text: body.slice(0, 600),
        url: url,
      });
    }
    return out;
  }

  /**
   * Our own storefront, walked the way a visitor walks it — the logic that
   * used to live in worker/store.mjs, moved in here because the page is the
   * only thing with a browser now.
   *
   * Same origin only: the agent can fetch the store's own pages when the web
   * view is already on the store (the brain sends `goto` first). From another
   * origin the browser would refuse the fetch, so this says so plainly rather
   * than returning an empty shop.
   *
   * The dedupe trap from store.mjs is kept: ?variant=… is the same product in
   * another colour, so links are keyed by pathname with search and hash gone.
   */
  var PRODUCT_PATH = /\/(products?|product|item|items|p|shop)\/[^/?#]+/i;
  var LISTING_PATH = /\/(collections?|categories?|category|shop|products|all)(\/[^/?#]+)?\/?$/i;

  function linksIn(doc, base) {
    var here = new URL(base).host;
    var seen = Object.create(null);
    var products = [];
    var listings = [];
    var as = doc.querySelectorAll("a[href]");
    for (var i = 0; i < as.length; i++) {
      var u;
      try {
        u = new URL(as[i].getAttribute("href"), base);
      } catch (e) {
        continue;
      }
      if (u.host !== here) continue;
      u.hash = "";
      u.search = "";
      if (seen[u.href]) continue;
      seen[u.href] = 1;
      if (PRODUCT_PATH.test(u.pathname)) products.push(u.href);
      else if (LISTING_PATH.test(u.pathname)) listings.push(u.href);
    }
    return { products: products, listings: listings };
  }

  function productFrom(doc, url) {
    var meta = function (sel) {
      var n = doc.querySelector(sel);
      var v = n && n.getAttribute("content");
      return v ? v.trim() : null;
    };
    var title = meta('meta[property="og:title"]');
    if (!title) {
      var h1 = doc.querySelector("h1");
      title = h1 ? text(h1) : null;
    }
    if (!title) title = doc.title || null;
    var image = meta('meta[property="og:image"]');
    if (!image) {
      var img = doc.querySelector("main img, img");
      image = img ? abs(img.getAttribute("src")) : null;
    }
    var price =
      meta('meta[property="product:price:amount"]') || meta('meta[property="og:price:amount"]');
    if (!price) {
      var ip = doc.querySelector('[itemprop="price"]');
      price = (ip && (ip.getAttribute("content") || text(ip))) || null;
    }
    if (!price) {
      var scope = doc.body || doc.documentElement;
      var pm = /(?:[$€£]\s?\d[\d,]*(?:\.\d{2})?|\d[\d,]*(?:\.\d{2})?\s?(?:USD|EUR|GBP))/.exec(
        text(scope),
      );
      price = pm ? pm[0] : null;
    }
    return {
      url: url,
      title: title ? String(title).trim() : null,
      price: price ? String(price).trim() : null,
      image: image,
    };
  }

  function fetchDoc(url) {
    return root
      .fetch(url, { credentials: "same-origin" })
      .then(function (r) {
        if (!r.ok) throw new Error("http " + r.status);
        return r.text();
      })
      .then(function (html) {
        return new root.DOMParser().parseFromString(html, "text/html");
      });
  }

  function store(url, opts) {
    opts = opts || {};
    var limit = opts.limit || 30;
    if (!url) return Promise.resolve({ products: [], stopped: "no store url" });
    var base;
    try {
      base = new URL(url, location.href);
    } catch (e) {
      return Promise.resolve({ products: [], stopped: "the store url is not a url" });
    }
    if (base.origin !== location.origin)
      return Promise.resolve({
        products: [],
        stopped: "not on the store — open " + base.origin + " first",
      });

    return fetchDoc(base.href)
      .then(function (doc) {
        var found = linksIn(doc, base.href);
        var chain = Promise.resolve(found.products.slice());
        found.listings.slice(0, 3).forEach(function (listing) {
          chain = chain.then(function (acc) {
            if (acc.length >= limit) return acc;
            return fetchDoc(listing)
              .then(function (d2) {
                var more = linksIn(d2, listing).products;
                more.forEach(function (p) {
                  if (acc.indexOf(p) < 0) acc.push(p);
                });
                return acc;
              })
              .catch(function () {
                return acc;
              });
          });
        });
        return chain;
      })
      .then(function (links) {
        links = links.slice(0, limit);
        var products = [];
        var chain = Promise.resolve();
        links.forEach(function (link) {
          chain = chain.then(function () {
            return fetchDoc(link)
              .then(function (d) {
                var p = productFrom(d, link);
                if (p.title) products.push(p);
              })
              .catch(function () {});
          });
        });
        return chain.then(function () {
          if (!products.length)
            return {
              products: products,
              stopped: links.length
                ? "the product pages did not read"
                : "no products found on the store",
            };
          return { products: products, stopped: null };
        });
      })
      .catch(function (e) {
        return { products: [], stopped: "the store did not open: " + ((e && e.message) || e) };
      });
  }

  O.read = {
    platform: platform,
    signedIn: signedIn,
    userId: userId,
    accountStatus: function () {
      var site = O.sites && O.sites.instagram;
      return site && site.readStatus ? site.readStatus() : null;
    },
    accountStatusUrl: function () {
      var site = O.sites && O.sites.instagram;
      return site ? site.statusUrl : null;
    },
    /* ------------------------------------------------- the supplier desk */

    /** Whoever the site on screen says its conversations are with. */
    threads: function () {
      var site = deskSite();
      return site && site.threads ? site.threads() : [];
    },

    /** The open conversation, oldest last. */
    messages: function () {
      var site = deskSite();
      return site && site.messages ? site.messages() : [];
    },

    /** What a search page on Alibaba or 1688 is showing. */
    results: function () {
      var site = O.sites && O.sites.alibaba;
      return site && site.results ? site.results() : [];
    },

    /**
     * The company or product page on screen, as printed: who they are, how
     * long they say they have traded, how fast they answer, what they have
     * sold, what certificates they list, whether they say OEM/ODM, and the
     * quantity -> price ladder when the page shows one. null when the page on
     * screen is not one of those.
     */
    supplier: function () {
      var site = O.sites && O.sites.alibaba;
      if (!site || !site.supplier || !site.match(location.hostname)) return null;
      return site.supplier();
    },

    handle: handle,
    bodyText: bodyText,
    posts: posts,
    tags: tags,
    ads: ads,
    store: store,
    captionOf: captionOf,
    text: text,
  };
})(window);

/* ---- agent/hands.js ---- */
/**
 * hands.js — scroll, tap, type, dwell.
 *
 * Nothing in this file decides WHEN to act. The brain decides; the hands
 * execute. Every action moves the cursor to the target first and waits a beat,
 * because that beat is the whole point: Alex is watching the wand move.
 *
 * Honest note about taps: events synthesised from a script always carry
 * isTrusted === false. There is no way to forge that from page JS — only the
 * user or the browser engine can. React and most sites listen for the event
 * pair anyway, so the sequence below works; where a site checks isTrusted, the
 * tap will not take, and tapEl reports back that nothing changed instead of
 * pretending it worked. el.click() is kept as a fallback for exactly that case
 * — see sig() for why it is not fired unconditionally.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.hands) return;

  var stopped = false;
  var sleep = function (ms) {
    return new Promise(function (r) {
      root.setTimeout(r, ms);
    });
  };

  function centerOf(el) {
    var r = el.getBoundingClientRect();
    return { x: r.left + r.width / 2, y: r.top + r.height / 2 };
  }

  function inView(el) {
    var r = el.getBoundingClientRect();
    var h = root.innerHeight || 844;
    return r.bottom > 8 && r.top < h - 8;
  }

  /**
   * scroll(px, {pace}) — human bursts with pauses, window.scrollBy in small
   * steps. Never scrollTo, never one jump.
   */
  function scroll(px, opts) {
    opts = opts || {};
    // the brain's paces: "read" is a slow browse, "skim" is a fast flick
    var pace = opts.pace || "easy";
    var perStep = pace === "skim" || pace === "fast" ? 34 : pace === "read" || pace === "slow" ? 12 : 22;
    var burst = pace === "skim" || pace === "fast" ? 9 : pace === "read" || pace === "slow" ? 4 : 6;
    var dir = px < 0 ? -1 : 1;
    var left = Math.abs(px);
    var steps = 0;
    return new Promise(function (done) {
      (function bursts() {
        if (stopped || left <= 0) return done({ moved: true, steps: steps });
        var n = 0;
        (function step() {
          if (stopped || left <= 0 || n >= burst) {
            if (stopped || left <= 0) return done({ moved: true, steps: steps });
            return sleep(160 + Math.random() * 260).then(bursts);
          }
          var amt = Math.min(left, perStep + Math.round(Math.random() * 8));
          root.scrollBy(0, dir * amt);
          left -= amt;
          n++;
          steps++;
          root.setTimeout(step, 16);
        })();
      })();
    });
  }

  function fire(el, type, pt, extra) {
    var Ctor =
      type.indexOf("pointer") === 0 && root.PointerEvent ? root.PointerEvent : root.MouseEvent;
    var init = {
      bubbles: true,
      cancelable: true,
      composed: true,
      view: root,
      clientX: pt.x,
      clientY: pt.y,
      screenX: pt.x,
      screenY: pt.y,
      button: 0,
      buttons: type === "pointerdown" || type === "mousedown" ? 1 : 0,
      detail: 1,
    };
    if (Ctor === root.PointerEvent) {
      init.pointerId = 1;
      init.pointerType = "touch";
      init.isPrimary = true;
      init.width = 1;
      init.height = 1;
      init.pressure = init.buttons ? 0.5 : 0;
    }
    if (extra) for (var k in extra) init[k] = extra[k];
    try {
      el.dispatchEvent(new Ctor(type, init));
    } catch (e) {
      /* a page that has broken the constructor is not worth crashing over */
    }
  }

  /**
   * A cheap signature of "did this control change state". Dispatching the
   * sequence AND calling el.click() would press a toggle twice — like, then
   * unlike — so el.click() is the fallback only: it runs when the dispatched
   * click changed nothing, which is the case on a site that ignores untrusted
   * events, and is skipped when the sequence already took.
   */
  function sig(el) {
    if (!el || !el.isConnected) return null;
    return (
      (el.getAttribute("aria-label") || "") +
      "|" + (el.getAttribute("aria-pressed") || "") +
      "|" + (el.getAttribute("aria-selected") || "") +
      "|" + ((el.innerText || el.textContent || "").slice(0, 40))
    );
  }

  var SEQ = [
    "pointerover",
    "pointerenter",
    "pointerdown",
    "mousedown",
    "pointerup",
    "mouseup",
    "click",
  ];

  function tapAt(px, py, opts) {
    opts = opts || {};
    return O.cursor.moveTo(px, py, { ms: opts.ms || 480 }).then(function () {
      return sleep(90 + Math.random() * 180);
    }).then(function () {
      return O.cursor.press();
    }).then(function () {
      var pt = { x: px, y: py };
      var target = document.elementFromPoint(px, py) || document.body;
      var before = target ? target.getAttribute("aria-label") : null;
      var s0 = sig(target);
      SEQ.forEach(function (t) {
        fire(target, t, pt);
      });
      if (target && target.isConnected && sig(target) === s0 && typeof target.click === "function") {
        try {
          target.click();
        } catch (e) {
          /* ignore */
        }
      }
      return {
        hit: !!target,
        stillThere: !!(target && target.isConnected),
        labelBefore: before,
        labelAfter: target && target.isConnected ? target.getAttribute("aria-label") : null,
        changed: !!(target && target.isConnected && target.getAttribute("aria-label") !== before),
      };
    });
  }

  function tapEl(el, opts) {
    if (!el) return Promise.resolve({ hit: false, stillThere: false, changed: false });
    var pre = Promise.resolve();
    if (!inView(el)) {
      // bring it on screen the way a thumb would, not with scrollIntoView
      var r = el.getBoundingClientRect();
      pre = scroll(Math.round(r.top - (root.innerHeight || 844) * 0.45), { pace: "easy" });
    }
    return pre.then(function () {
      var c = centerOf(el);
      var before = el.getAttribute("aria-label");
      return O.cursor
        .moveTo(c.x, c.y, { ms: (opts && opts.ms) || 520 })
        .then(function () {
          return sleep(90 + Math.random() * 200);
        })
        .then(function () {
          return O.cursor.press();
        })
        .then(function () {
          var pt = centerOf(el);
          var under = document.elementFromPoint(pt.x, pt.y);
          var target = under && el.contains(under) ? under : el;
          var s0 = sig(el);
          SEQ.forEach(function (t) {
            fire(target, t, pt);
          });
          if (el.isConnected && sig(el) === s0 && typeof el.click === "function") {
            try {
              el.click();
            } catch (e) {
              /* ignore */
            }
          }
          return sleep(60);
        })
        .then(function () {
          var after = el.isConnected ? el.getAttribute("aria-label") : null;
          return {
            hit: true,
            stillThere: !!el.isConnected,
            labelBefore: before,
            labelAfter: after,
            changed: after !== before,
          };
        });
    });
  }

  /** The native value setter, so React's own onChange sees the write. */
  function setValue(el, v) {
    var proto =
      el instanceof root.HTMLTextAreaElement
        ? root.HTMLTextAreaElement.prototype
        : root.HTMLInputElement.prototype;
    var desc = Object.getOwnPropertyDescriptor(proto, "value");
    if (desc && desc.set) desc.set.call(el, v);
    else el.value = v;
  }

  /**
   * type(text, {into, strokes, delays, typos})
   *
   * `strokes` is what the brain actually sends: [{key, delayMs}], where a key
   * of "\b" is a backspace. The strokes ARE the rhythm — they are played back
   * exactly, and nothing here invents timing of its own.
   * `delays` + `typos` are the older, simpler form and are turned into the
   * same strokes: one ms per character (a short array repeats its last value),
   * and {at, ch} for a wrong character typed at that index then backspaced.
   * The only field this ever reads back is the one it typed into.
   */
  function type(text, opts) {
    opts = opts || {};
    var el =
      opts.into && typeof opts.into === "string"
        ? document.querySelector(opts.into)
        : opts.into || document.activeElement;
    if (!el) return Promise.resolve({ ok: false, error: "no field" });
    text = String(text == null ? "" : text);
    var delays = Array.isArray(opts.delays) ? opts.delays : [];
    var typos = Array.isArray(opts.typos) ? opts.typos : [];
    var at = function (i) {
      if (!delays.length) return 55; // brain sent nothing: one flat fallback
      return delays[Math.min(i, delays.length - 1)];
    };
    var editable = el.isContentEditable && !("value" in el);

    // strokes win when they are there; otherwise the text + delays form
    var strokes = Array.isArray(opts.strokes) ? opts.strokes.slice() : null;
    if (!strokes) {
      strokes = [];
      for (var si = 0; si < text.length; si++) {
        for (var ti = 0; ti < typos.length; ti++)
          if (typos[ti].at === si) {
            strokes.push({ key: typos[ti].ch, delayMs: at(si) });
            strokes.push({ key: "\b", delayMs: typos[ti].pause || at(si) * 3 });
          }
        strokes.push({ key: text.charAt(si), delayMs: at(si) });
      }
    }

    var write = function (v) {
      if (editable) el.textContent = v;
      else setValue(el, v); // the native setter, so React notices
      el.dispatchEvent(new root.Event("input", { bubbles: true, composed: true }));
    };

    var c = centerOf(el);
    return O.cursor
      .moveTo(c.x, c.y, { ms: 460 })
      .then(function () {
        return O.cursor.press();
      })
      .then(function () {
        try {
          el.focus();
        } catch (e) {
          /* ignore */
        }
        var cur = "";
        var i = 0;
        return new Promise(function (done) {
          (function next() {
            if (stopped || i >= strokes.length) {
              el.dispatchEvent(new root.Event("change", { bubbles: true }));
              // the one field the agent ever reads: the box it just typed into
              return done({ ok: true, typed: editable ? el.textContent : el.value });
            }
            var st = strokes[i++] || {};
            var wait = st.delayMs == null ? 55 : st.delayMs;
            root.setTimeout(function () {
              if (st.key === "\b" || st.key === "Backspace") cur = cur.slice(0, -1);
              else cur += st.key == null ? "" : String(st.key);
              write(cur);
              next();
            }, wait);
          })();
        });
      });
  }

  /**
   * A data URL or a blob, turned into the bytes a file input wants.
   * Anything that is not one of those is refused rather than guessed at.
   */
  function toBlob(src) {
    if (!src) return Promise.resolve(null);
    if (root.Blob && src instanceof root.Blob) return Promise.resolve(src);
    var s = String(src);
    if (/^data:/.test(s)) {
      var m = /^data:([^;,]*)(;base64)?,([\s\S]*)$/.exec(s);
      if (!m) return Promise.resolve(null);
      var type = m[1] || "application/octet-stream";
      var body = m[3];
      try {
        if (m[2]) {
          var bin = root.atob(body);
          var bytes = new Uint8Array(bin.length);
          for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
          return Promise.resolve(new root.Blob([bytes], { type: type }));
        }
        return Promise.resolve(new root.Blob([decodeURIComponent(body)], { type: type }));
      } catch (e) {
        return Promise.resolve(null);
      }
    }
    if (/^blob:/.test(s)) {
      // a blob: URL only resolves through a fetch, and only same-origin
      return root
        .fetch(s)
        .then(function (r) { return r.blob(); })
        .catch(function () { return null; });
    }
    return Promise.resolve(null);
  }

  function extFor(type) {
    return { "image/png": "png", "image/jpeg": "jpg", "image/webp": "webp", "image/gif": "gif", "application/pdf": "pdf" }[type] || "bin";
  }

  /**
   * sendFile({file, name, selector}) — hand the page a picture.
   *
   * Suppliers ask for the render and for his WeChat QR, and both message
   * centres take them through a plain <input type="file"> behind the paperclip.
   * There is no way to fake a real file chooser from page JS, so this does the
   * one thing that works: builds a DataTransfer, puts the File in it, assigns
   * it to input.files and fires input+change so the site's own uploader picks
   * it up. That is the same object the browser would have handed it.
   *
   * It never picks a file off the disk and never invents one: `file` is a data
   * URL or a Blob the app already fetched into the page. When there is no file
   * input on screen, or the browser will not let files be assigned, it says so
   * — { ok: false, error } — rather than reporting a send that never happened.
   */
  function sendFile(opts) {
    opts = opts || {};
    var input = null;
    if (opts.selector) input = document.querySelector(opts.selector);
    if (!input) {
      var desk = null;
      var all = O.sites || {};
      for (var key in all) {
        if (all[key] && typeof all[key].match === "function" && all[key].match(location.hostname)) desk = all[key];
      }
      if (desk && desk.fileInput) input = desk.fileInput();
    }
    if (!input) {
      var any = document.querySelectorAll('input[type="file"]');
      for (var i = 0; i < any.length && !input; i++) if (!any[i].disabled) input = any[i];
    }
    if (!input) return Promise.resolve({ ok: false, error: "no file input on this page" });
    if (!root.DataTransfer || !root.File)
      return Promise.resolve({ ok: false, error: "this browser will not let a file be attached" });

    return toBlob(opts.file || opts.dataUrl || opts.blob).then(function (blob) {
      if (!blob) return { ok: false, error: "no file: expected a data: url or a blob" };
      var name = String(opts.name || "image." + extFor(blob.type));
      var file;
      try {
        file = new root.File([blob], name, { type: blob.type || "application/octet-stream" });
      } catch (e) {
        return { ok: false, error: "could not build the file: " + ((e && e.message) || e) };
      }
      var dt;
      try {
        dt = new root.DataTransfer();
        dt.items.add(file);
        input.files = dt.files;
      } catch (e2) {
        return { ok: false, error: "the page would not take the file: " + ((e2 && e2.message) || e2) };
      }
      if (!input.files || input.files.length !== 1)
        return { ok: false, error: "the file did not stick to the input" };
      try {
        input.dispatchEvent(new root.Event("input", { bubbles: true, composed: true }));
        input.dispatchEvent(new root.Event("change", { bubbles: true, composed: true }));
      } catch (e3) {
        return { ok: false, error: "could not tell the page about the file" };
      }
      return { ok: true, name: name, type: blob.type || null, bytes: blob.size == null ? null : blob.size };
    });
  }

  function dwell(ms) {
    return O.cursor.breathe(Math.max(0, ms | 0)).then(function () {
      return { waited: ms | 0 };
    });
  }

  O.hands = {
    scroll: scroll,
    tapAt: tapAt,
    tapEl: tapEl,
    type: type,
    sendFile: sendFile,
    dwell: dwell,
    centerOf: centerOf,
    stop: function () {
      stopped = true;
    },
    resume: function () {
      stopped = false;
    },
    stopped: function () {
      return stopped;
    },
  };
})(window);

/* ---- agent/panel.js ---- */
/**
 * panel.js — the board, inside the glass.
 *
 * One row per job on the shortlist: what it is, what it pays an hour, and the
 * reply Claude drafted for it. Take is a button, and it is the only way work
 * is ever accepted — nothing on this screen fires on its own. That is not a UI
 * preference, it is the line the whole app is built on: Fiverr bans automated
 * order fulfilment, so the accepting is a person tapping a thing.
 *
 * It computes nothing. Every value here is pushed by the brain, and a reload
 * starts again from whatever the brain says next. A panel that kept its own
 * copy of the board would eventually show a job that no longer exists and
 * offer a button that takes it.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});
  if (O.panel) return;

  var ID = "__clone_panel";
  var Z = 2147483645;
  var node = null;
  var open = false;

  /** Exactly what the brain pushes. Nothing is stored and nothing is derived. */
  var state = {
    build: null,
    working: false,     // inside the seller's hours
    resting: null,      // why it is idle, in words, when it is
    doing: null,        // the one line under the title
    takenToday: 0,
    takeBudget: 0,
    board: [],          // [{id, title, buyer, why, label, wand, pays, reply, ready, questions}]
  };

  function send(message) {
    try { root.webkit.messageHandlers.organic.postMessage(message); } catch (e) {}
  }

  function el(tag, cls, text) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
  }

  function money(cents) {
    if (cents == null) return null;
    return "$" + (cents / 100).toFixed(cents % 100 ? 2 : 0);
  }

  function styles() {
    if (document.getElementById(ID + "_css")) return;
    var css = el("style");
    css.id = ID + "_css";
    css.textContent = [
      "#" + ID + "{position:fixed;left:0;right:0;bottom:0;z-index:" + Z + ";",
      "  font:13px/1.45 -apple-system,'SF Pro Text',system-ui,sans-serif;color:#0B0C0E;",
      "  background:rgba(252,252,253,.92);backdrop-filter:blur(30px) saturate(1.6);",
      "  -webkit-backdrop-filter:blur(30px) saturate(1.6);",
      "  border-top:1px solid rgba(11,12,14,.1);box-shadow:0 -14px 40px -24px rgba(11,12,14,.45);",
      "  transform:translateY(calc(100% - 46px));transition:transform .26s cubic-bezier(.2,.8,.3,1);}",
      "#" + ID + ".is-open{transform:translateY(0)}",
      "#" + ID + " .cl-bar{height:46px;display:flex;align-items:center;gap:10px;padding:0 16px;cursor:pointer;user-select:none}",
      "#" + ID + " .cl-dot{width:8px;height:8px;border-radius:50%;background:#C8CBD0;flex:none}",
      "#" + ID + " .cl-dot.on{background:#0F9D58}",
      "#" + ID + " .cl-name{font-weight:700;letter-spacing:-.01em}",
      "#" + ID + " .cl-doing{color:rgba(11,12,14,.55);flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
      "#" + ID + " .cl-count{font-variant-numeric:tabular-nums;color:rgba(11,12,14,.45)}",
      "#" + ID + " .cl-body{max-height:min(62vh,540px);overflow:auto;padding:4px 16px 18px}",
      "#" + ID + " .cl-rest{padding:10px 0 4px;color:rgba(11,12,14,.5)}",
      "#" + ID + " .cl-job{border-top:1px solid rgba(11,12,14,.09);padding:13px 0}",
      "#" + ID + " .cl-top{display:flex;align-items:baseline;gap:8px}",
      "#" + ID + " .cl-title{font-weight:650;flex:1;min-width:0}",
      "#" + ID + " .cl-pays{font-weight:700;font-variant-numeric:tabular-nums;flex:none}",
      "#" + ID + " .cl-why{color:rgba(11,12,14,.5);margin-top:2px}",
      "#" + ID + " .cl-tag{display:inline-block;margin-right:6px;padding:1px 7px;border-radius:999px;",
      "  background:rgba(11,12,14,.06);font-size:11px;font-weight:700;letter-spacing:.02em}",
      "#" + ID + " .cl-tag.wand{background:rgba(120,60,200,.12);color:#5B2CA8}",
      "#" + ID + " .cl-tag.ask{background:rgba(224,140,10,.14);color:#8A5300}",
      "#" + ID + " .cl-reply{margin-top:8px;padding:9px 11px;border-radius:10px;background:rgba(11,12,14,.04);",
      "  white-space:pre-wrap;max-height:120px;overflow:auto;color:rgba(11,12,14,.78)}",
      "#" + ID + " .cl-acts{display:flex;gap:8px;margin-top:9px}",
      "#" + ID + " button.cl-b{border:0;border-radius:9px;padding:8px 14px;font:inherit;font-weight:650;cursor:pointer}",
      "#" + ID + " .cl-take{background:#0B0C0E;color:#fff}",
      "#" + ID + " .cl-skip{background:rgba(11,12,14,.07);color:#0B0C0E}",
      "#" + ID + " .cl-empty{padding:18px 0;color:rgba(11,12,14,.45)}",
    ].join("");
    document.documentElement.appendChild(css);
  }

  function draw() {
    styles();
    if (!node || !node.isConnected) {
      node = el("div");
      node.id = ID;
      document.documentElement.appendChild(node);
    }
    node.textContent = "";
    node.className = open ? "is-open" : "";

    var bar = el("div", "cl-bar");
    var dot = el("span", "cl-dot" + (state.working ? " on" : ""));
    bar.appendChild(dot);
    bar.appendChild(el("span", "cl-name", "Clone Me"));
    bar.appendChild(el("span", "cl-doing", state.doing || (state.working ? "looking at the board" : "off the clock")));
    bar.appendChild(el("span", "cl-count", state.takenToday + "/" + state.takeBudget + " today"));
    bar.onclick = function () { open = !open; draw(); };
    node.appendChild(bar);

    var body = el("div", "cl-body");

    // Why it is doing nothing is more useful than a spinner. "Asleep until
    // 09:30" is an answer; a blank board is a bug report waiting to happen.
    if (state.resting) body.appendChild(el("div", "cl-rest", state.resting));

    if (!state.board.length) {
      body.appendChild(el("div", "cl-empty", state.working ? "Nothing on the board it can do." : "Not working right now."));
    }

    state.board.forEach(function (job) {
      var row = el("div", "cl-job");

      var top = el("div", "cl-top");
      top.appendChild(el("span", "cl-title", job.title || "(untitled)"));
      var pays = money(job.pays);
      if (pays) top.appendChild(el("span", "cl-pays", pays));
      row.appendChild(top);

      var why = el("div", "cl-why");
      if (job.wand) why.appendChild(el("span", "cl-tag wand", "WAND"));
      if (job.ready === false) why.appendChild(el("span", "cl-tag ask", "NEEDS AN ANSWER"));
      why.appendChild(document.createTextNode([job.label, job.why].filter(Boolean).join(" · ")));
      row.appendChild(why);

      // The drafted reply is shown in full before anything can be taken. A
      // Take button over a reply nobody read is the same as no button at all.
      if (job.reply) row.appendChild(el("div", "cl-reply", job.reply));
      if (job.questions && job.questions.length) {
        row.appendChild(el("div", "cl-reply", job.questions.map(function (q) { return "· " + q; }).join("\n")));
      }

      var acts = el("div", "cl-acts");
      var take = el("button", "cl-b cl-take", job.ready === false ? "Send the questions" : "Take it");
      take.onclick = function () { send({ t: "take", id: job.id }); };
      var skip = el("button", "cl-b cl-skip", "Skip");
      skip.onclick = function () { send({ t: "skip", id: job.id }); };
      acts.appendChild(take);
      acts.appendChild(skip);
      row.appendChild(acts);

      body.appendChild(row);
    });

    node.appendChild(body);
  }

  O.panel = {
    /** The brain pushes the whole state. The panel never patches its own. */
    set: function (next) {
      state = Object.assign({}, state, next || {});
      if (!Array.isArray(state.board)) state.board = [];
      draw();
    },
    open: function () { open = true; draw(); },
    close: function () { open = false; draw(); },
    mount: draw,
  };
})(window);

/* ---- agent/index.js ---- */
/**
 * index.js — the entry. Builds window.__organic, wires the bridge, boots the
 * pieces.
 *
 * This bundle is injected at document start into EVERY frame and on EVERY
 * navigation, so it must be idempotent twice over: it runs only in the top
 * frame, and a second run on the same window is a no-op.
 *
 * It stores nothing, logs nothing that came out of a field, and never reads an
 * input's value except the comment box hands.type() just wrote to.
 */
(function (root) {
  "use strict";
  var O = root.__organicNS || (root.__organicNS = {});

  // Only the top frame. An iframe gets the script too and must stay silent.
  try {
    if (root.top !== root.self) return;
  } catch (e) {
    return; // cross-origin parent: not the top frame we own
  }
  if (root.__organic && root.__organic.__booted) return;

  /** Post to Swift. In a plain browser (and in the tests) there is no handler. */
  function send(msg) {
    var text;
    try {
      text = JSON.stringify(msg);
    } catch (e) {
      return false;
    }
    try {
      if (
        root.webkit &&
        root.webkit.messageHandlers &&
        root.webkit.messageHandlers.organic &&
        typeof root.webkit.messageHandlers.organic.postMessage === "function"
      ) {
        root.webkit.messageHandlers.organic.postMessage(text);
        return true;
      }
    } catch (e) {
      /* the handler can vanish mid-navigation; never let that throw */
    }
    (root.__organic.sent = root.__organic.sent || []).push(msg);
    if (root.__organic.sent.length > 200) root.__organic.sent.shift();
    return false;
  }
  O.send = send;

  function tick(who, what) {
    O.panel.tick(who, what);
    send({ t: "tick", who: who, what: what });
  }

  /** The named things the brain taps: like, comment, next, profile. */
  function targetEl(name, a) {
    if (a && a.selector) return document.querySelector(a.selector);
    var s = O.sites[O.read.platform()];
    if (!s) return null;
    if (name === "like") return s.likeButton();
    if (name === "comment") return s.commentBox();
    if (name === "profile") return s.profileLink ? s.profileLink() : null;
    if (name === "reel") return s.openReel();
    return null;
  }

  var ACTS = {
    goto: function (a) {
      if (!a.url) throw new Error("goto needs a url");
      location.assign(a.url);
      return { going: a.url };
    },
    scroll: function (a) {
      return O.hands.scroll(a.px == null ? root.innerHeight : a.px, { pace: a.pace });
    },
    tap: function (a) {
      if (a.x != null && a.y != null)
        return O.hands.tapAt(a.x, a.y, a).then(function (r) {
          return { found: !!r.hit, changed: !!r.changed };
        });
      var name = a.target || a.what || null;
      var site = O.sites[O.read.platform()];
      // "next" is not a button on mobile: a reel advances by one viewport.
      if (name === "next") {
        var how = site && site.nextReel ? site.nextReel() : null;
        if (!how) return { found: false, changed: false };
        var y0 = root.scrollY;
        return O.hands.scroll(how.px, { pace: "skim" }).then(function () {
          return { found: true, changed: root.scrollY !== y0 };
        });
      }
      var el = targetEl(name, a);
      if (!el) return { found: false, changed: false }; // never a guess
      return O.hands.tapEl(el, a).then(function (r) {
        return { found: true, changed: !!r.changed, stillThere: !!r.stillThere };
      });
    },

    type: function (a) {
      var into = a.selector || null;
      var name = a.into || a.what || "comment";
      if (!into) into = targetEl(name === "comment" ? "comment" : name, {});
      if (!into) return { ok: false, error: "no field: " + name };
      // The brain sends the rhythm as strokes; the hands only play it.
      return O.hands.type(a.text, {
        into: into,
        strokes: a.strokes,
        delays: a.delays,
        typos: a.typos,
      });
    },

    /**
     * Send a message in whatever conversation is open.
     *
     * Deliberately dumb about WHO: opening the right thread is a separate,
     * visible step, so a message can never land in the wrong conversation
     * because a name matched loosely. If no composer is on screen it says so
     * and sends nothing.
     *
     * The text is typed keystroke by keystroke at the brain's pace — never
     * pasted. A composer filled instantly is the loudest automation signal
     * there is, and this is his own account.
     */
    send: function (a) {
      var desk = null;
      var all = O.sites || {};
      for (var key in all) {
        if (all[key] && typeof all[key].match === "function" && all[key].match(location.hostname)) desk = all[key];
      }
      var box = desk && desk.composer ? desk.composer() : null;
      if (!box) return Promise.resolve({ ok: false, error: "no message box on this page" });
      var body = String(a.text == null ? "" : a.text);
      if (!body.trim()) return Promise.resolve({ ok: false, error: "nothing to say" });

      return O.hands.type(body, { into: box, strokes: a.strokes, delays: a.delays, typos: a.typos }).then(function (r) {
        if (!r || !r.ok) return { ok: false, error: (r && r.error) || "could not type" };
        if (a.hold) return { ok: true, typed: r.typed, sent: false };
        // Enter sends on both WhatsApp Web and the Alibaba message centre.
        ["keydown", "keypress", "keyup"].forEach(function (type) {
          box.dispatchEvent(
            new root.KeyboardEvent(type, { key: "Enter", code: "Enter", keyCode: 13, which: 13, bubbles: true }),
          );
        });
        return { ok: true, typed: r.typed, sent: true };
      });
    },

    /**
     * Hand the page a picture — the product render, his WeChat QR.
     *
     * The file arrives from the app as a data URL already in the page; this
     * only attaches it to the site's own file input. If the message centre is
     * not open, or the paperclip has not been pressed and no input exists, it
     * says so and sends nothing.
     */
    sendFile: function (a) {
      return O.hands.sendFile({
        file: a.file || a.dataUrl || a.blob,
        name: a.name,
        selector: a.selector,
      });
    },

    /** Open a conversation by the exact name the list shows. */
    openThread: function (a) {
      var all = O.sites || {};
      for (var key in all) {
        var site = all[key];
        if (site && typeof site.match === "function" && site.match(location.hostname) && site.openThread) {
          return { ok: Boolean(site.openThread(String(a.who || ""))) };
        }
      }
      return { ok: false, error: "this page has no conversation list" };
    },

    dwell: function (a) {
      return O.hands.dwell(a.ms == null ? 800 : a.ms);
    },
    read: function (a) {
      var what = a.what || "page";
      if (what === "posts") return O.read.posts();
      if (what === "tags") return O.read.tags();
      if (what === "text") return O.read.bodyText(4000);
      if (what === "ads") return O.read.ads();
      if (what === "store") return O.read.store(a.url, a);
      if (what === "handle") return O.read.handle(a.platform);
      if (what === "signedIn") return O.read.signedIn(a.platform);
      if (what === "userId") return O.read.userId();
      if (what === "accountStatus") return O.read.accountStatus();
      if (what === "accountStatusUrl") return O.read.accountStatusUrl();
      if (what === "threads") return O.read.threads();
      if (what === "messages") return O.read.messages();
      if (what === "results") return O.read.results();

      /*
       * The desk's own vocabulary.
       *
       * The brain asks for "listings" and "thread"; the readers above produce
       * "results" and "messages" in the shapes the pages actually give. These
       * two lines are the seam between them, and they are a seam rather than
       * a rename because the shapes differ too: a listing needs a name to be
       * worth keeping, and a message needs a direction before anything it
       * says can be filed as a supplier's answer.
       */
      if (what === "listings") {
        return O.read.results().map(function (r) {
          return {
            // The supplier is the name; the product title is not a company.
            name: r.supplier || null,
            url: r.url,
            title: r.title,
            blurb: r.title,
            tags: null,
            years: r.years,
            price: r.price,
            moq: r.moq,
            transactions: r.transactions,
            site: r.site,
          };
        });
      }
      if (what === "thread") {
        // Opening by the exact printed name first: reading the wrong
        // conversation is how a supplier's words get filed under another's.
        var site = null;
        var all = O.sites || {};
        for (var key in all) {
          if (all[key] && typeof all[key].match === "function" && all[key].match(location.hostname)) site = all[key];
        }
        if (a.who && site && site.openThread) site.openThread(String(a.who));
        return O.read.messages().map(function (m, i) {
          return {
            id: String(m.at || "") + "#" + i + "#" + String(m.text || "").slice(0, 24),
            // Unknown stays unknown: a message whose side the page did not
            // state is never filed as a supplier's reply.
            dir: m.mine === true ? "out" : m.mine === false ? "in" : "unknown",
            text: m.text,
            at: m.at,
          };
        });
      }
      if (what === "supplier") return O.read.supplier();
      return O.read.handle(a.platform).then(function (h) {
        return {
          url: location.href,
          platform: O.read.platform(),
          signedIn: O.read.signedIn(),
          handle: h,
          posts: O.read.posts(),
          tags: O.read.tags(),
        };
      });
    },

    say: function (a) {
      tick(a.who || "crew", a.what || "");
      return { said: true };
    },
    cursor: function (a) {
      if (a.label || a.name) O.cursor.setName(a.label || a.name);
      if (a.press) return O.cursor.press();
      if (a.x != null && a.y != null) return O.cursor.moveTo(a.x, a.y, { ms: a.ms });
      return O.cursor.at();
    },
    panel: function (a) {
      // `show` is tri-state: true opens, false closes, undefined just redraws.
      O.panel.set(a);
      if (a.show === true) O.panel.open();
      else if (a.show === false) O.panel.close();
      return { open: O.panel.isOpen() };
    },

    stop: function (a) {
      if (a.resume) {
        O.hands.resume();
        O.panel.set({ stopped: false, paused: false });
        return { stopped: false };
      }
      O.hands.stop();
      O.panel.set({ stopped: true });
      return { stopped: true };
    },
  };

  function fromApp(jsonText) {
    var msg;
    try {
      msg = typeof jsonText === "string" ? JSON.parse(jsonText) : jsonText;
    } catch (e) {
      return false;
    }
    if (!msg || msg.t !== "do") return false;
    var id = msg.id;
    var fn = ACTS[msg.act];
    if (!fn) {
      send({ t: "done", id: id, ok: false, result: null, error: "unknown act: " + msg.act });
      return false;
    }
    // `stop` must land even while something is in flight, so nothing is queued.
    Promise.resolve()
      .then(function () {
        return fn(msg);
      })
      .then(function (result) {
        send({ t: "done", id: id, ok: true, result: result == null ? null : result, error: null });
      })
      .catch(function (err) {
        send({
          t: "done",
          id: id,
          ok: false,
          result: null,
          error: (err && err.message) || String(err),
        });
      });
    return true;
  }

  function hello() {
    var base = {
      t: "hello",
      url: location.href,
      platform: O.read.platform(),
      signedIn: O.read.signedIn(),
    };
    return O.read
      .handle()
      .then(function (h) {
        base.handle = h;
        send(base);
        return base;
      })
      .catch(function () {
        base.handle = null;
        send(base);
        return base;
      });
  }

  /**
   * What the site answers when something fails.
   *
   * Alex saw Instagram's own "an unexpected error occurred" and asked whether
   * the log showed the response. It did not: the log carried what the crew
   * said and nothing the site said back. So the page watches its own network
   * now — only failures, only the status and the first words of the body,
   * never a form field and never anything he typed. A refused login is a
   * fact worth having; it is also usually not an account problem at all.
   */
  function watchNetwork() {
    if (root.__organicNetWatched) return;
    root.__organicNetWatched = true;
    var realFetch = root.fetch;
    if (typeof realFetch !== "function") return;
    root.fetch = function (input, init) {
      var url = "";
      try { url = typeof input === "string" ? input : (input && input.url) || ""; } catch (e) { url = ""; }
      return realFetch.apply(this, arguments).then(function (res) {
        try {
          var interesting = res && (res.status >= 400 || /login|challenge|checkpoint|accounts\/login/i.test(url));
          if (interesting && res.status >= 400) {
            var copy = res.clone();
            copy.text().then(function (body) {
              send({
                t: "trouble",
                what: "the site refused " + short(url) + " with " + res.status + (body ? ": " + String(body).slice(0, 180) : ""),
              });
            }).catch(function () {
              send({ t: "trouble", what: "the site refused " + short(url) + " with " + res.status });
            });
          }
        } catch (e) { /* watching must never break the page */ }
        return res;
      });
    };
  }

  function short(url) {
    try { var u = new URL(url, location.href); return u.hostname + u.pathname.slice(0, 60); } catch (e) { return String(url).slice(0, 60); }
  }

  watchNetwork();

  root.__organic = {
    __booted: true,
    version: 1,
    fromApp: fromApp,
    send: send,
    ns: O,
    // handy for the app and the tests; none of these keep state anywhere
    cursor: O.cursor,
    hands: O.hands,
    read: O.read,
    panel: O.panel,
    sites: O.sites,
    find: O.find,
    bezel: O.bezel,
    hello: hello,
  };

  function boot() {
    O.bezel.mount();
    O.cursor.mount();
    O.panel.mount();
    hello();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot, { once: true });
  } else {
    boot();
  }
})(window);

